const SUBJECTS = {
  physics: { name:'Physics HL', short:'Physics', icon:'φ', color:'#587b96', tint:'#dfe9ee', groups:{
    'A · Space, Time & Motion':[
      ['A1.1','Position, velocity and acceleration','Kinematics'],['A1.2','Distance and displacement','Kinematics'],['A1.3','SUVAT equations and uniform acceleration','Kinematics'],['A1.4','Projectile motion and fluid resistance','Kinematics'],['A2.1',"Newton's three laws of motion",'Forces'],['A2.2','Free-body diagrams and resultant force','Forces'],['A2.3','Contact and field forces','Forces'],['A2.4','Momentum, impulse and conservation','Forces'],['A2.5','Elastic and inelastic collisions','Forces'],['A2.6','Circular motion and centripetal force','Forces'],['A3.1','Work, energy and power','Energy'],['A3.2','Conservation of energy and efficiency','Energy'],['A4.1','Rotational kinematics and torque','Rigid bodies'],['A4.2','Angular momentum','Rigid bodies'],['A5.1','Galilean and special relativity','Relativity']],
    'B · Particulate Nature of Matter':[
      ['B1.1','Thermal energy and temperature','Thermal'],['B1.2','Specific heat capacity and phase change','Thermal'],['B2.1','Greenhouse effect and energy balance','Climate'],['B3.1','Gas laws and kinetic model','Gas'],['B4.1','Thermodynamics and entropy','Thermodynamics'],['B5.1','Electric current and circuits','Current']],
    'C · Wave Behaviour':[
      ['C1.1','Simple harmonic motion','Oscillations'],['C1.2','Energy changes in SHM','Oscillations'],['C2.1','Wave model and wave equation','Waves'],['C2.2','Superposition and standing waves','Waves'],['C3.1','Refraction and diffraction','Wave phenomena'],['C4.1','Doppler effect','Wave phenomena'],['C5.1','Resonance and damping','Resonance']],
    'D · Fields':[
      ['D1.1','Gravitational fields and potential','Gravitation'],['D2.1','Electric fields and potential','Electric'],['D3.1','Motion in electromagnetic fields','EM fields'],['D4.1','Induction and magnetic flux','Induction'],['D5.1','DC circuit analysis','Circuits']],
    'E · Nuclear & Quantum Physics':[
      ['E1.1','Atomic structure and spectra','Atomic'],['E2.1','Quantum physics and photoelectric effect','Quantum'],['E3.1','Radioactive decay','Nuclear'],['E4.1','Fission, fusion and mass defect','Nuclear'],['E5.1','Standard model of particle physics','Particle']]
  }},
  math: { name:'Math AA HL', short:'Mathematics', icon:'∑', color:'#bd6549', tint:'#f2ded7', groups:{
    'Topic 1 · Number & Algebra':[
      ['SL 1.1','Scientific notation','Algebra'],['SL 1.2','Arithmetic sequences and series','Sequences'],['SL 1.3','Geometric sequences and series','Sequences'],['SL 1.4','Financial applications','Finance'],['SL 1.5','Laws of exponents and logarithms','Algebra'],['SL 1.6','Simple deductive proof','Proof'],['SL 1.7','Solving exponential equations','Algebra'],['SL 1.8','Infinite convergent geometric series','Sequences'],['SL 1.9','Binomial theorem','Algebra'],['AHL 1.10','Fractional and negative binomial expansions','Algebra · HL'],['AHL 1.15','Proof by induction and contradiction','Proof · HL'],['AHL 1.16','Systems of 3×3 linear equations','Algebra · HL']],
    'Topic 2 · Functions':[
      ['SL 2.1','Straight lines; parallel and perpendicular','Functions'],['SL 2.2','Domain, range and inverse','Functions'],['SL 2.3','Graph sketching with technology','Functions'],['SL 2.4','Key features of graphs','Functions'],['SL 2.5','Composite and inverse functions','Functions'],['SL 2.6','Quadratic functions and graphs','Functions'],['SL 2.7','Quadratic equations and inequalities','Functions'],['SL 2.8','Rational functions and asymptotes','Functions'],['SL 2.9','Exponential and logarithmic functions','Functions'],['SL 2.10','Solving equations graphically and analytically','Functions'],['SL 2.11','Transformations of graphs','Functions'],['AHL 2.12',"Polynomials, Vieta's formulas",'Functions · HL'],['AHL 2.13','Advanced rational functions','Functions · HL'],['AHL 2.14','Odd/even functions and domain restriction','Functions · HL'],['AHL 2.15','Functional inequalities','Functions · HL'],['AHL 2.16','Absolute value and reciprocal graphs','Functions · HL']],
    'Topic 3 · Geometry & Trigonometry':[
      ['SL 3.1','3D geometry, surface area and volume','Geometry'],['SL 3.2','Sine rule, cosine rule and triangle area','Trigonometry'],['SL 3.3','Applications and bearings','Trigonometry'],['SL 3.4','Radian measure, arc length and sector area','Trigonometry'],['SL 3.5','Unit circle and exact values','Trigonometry'],['AHL 3.7','Compound angle identities','Trigonometry · HL'],['AHL 3.8','Solving advanced trigonometric equations','Trigonometry · HL']],
    'Topic 4 · Statistics & Probability':[
      ['SL 4.1','Sampling methods and bias','Statistics'],['SL 4.2','Data presentation and interpretation','Statistics'],['SL 4.3','Mean, variance and standard deviation','Statistics'],['SL 4.4','Correlation and regression','Statistics'],['SL 4.7','Probability and Venn diagrams','Probability'],['AHL 4.12','Discrete and continuous distributions','Probability · HL']],
    'Topic 5 · Calculus':[
      ['SL 5.1','Limits and derivatives','Calculus'],['SL 5.2','Differentiation rules','Calculus'],['SL 5.3','Applications of differentiation','Calculus'],['SL 5.5','Integration and area','Calculus'],['AHL 5.12','Implicit and parametric differentiation','Calculus · HL'],['AHL 5.14','Integration by parts and substitution','Calculus · HL'],['AHL 5.17','Differential equations','Calculus · HL']]
  }},
  cs: { name:'Computer Science HL', short:'Computer Science', icon:'⌘', color:'#d6a44f', tint:'#f2e8c9', groups:{
    'A1 · Computer Fundamentals':[
      ['A1.1.1','Explain CPU components: ALU, CU, registers and buses','Hardware'],['A1.1.2','Explain the role of a GPU','Hardware'],['A1.1.3','Compare CPU and GPU architecture and use cases','Hardware · HL'],['A1.1.4','Explain the purpose of RAM, ROM, cache and registers','Memory'],['A1.1.5','Explain the fetch–decode–execute cycle','CPU'],['A1.1.6','Explain instruction pipelining','CPU · HL'],['A1.1.7','Compare secondary storage technologies','Storage'],['A1.1.8','Explain lossy and lossless compression, RLE and transform coding','Data'],['A1.1.9','Distinguish SaaS, PaaS and IaaS','Cloud'],['A1.2.1','Convert and represent data in binary and hexadecimal','Representation'],['A1.2.2','Explain how integers, text, images, audio and video are stored','Representation'],['A1.2.3','Explain the purpose and use of logic gates','Logic'],['A1.2.4','Construct truth tables and simplify expressions using K-maps','Logic'],['A1.2.5','Construct logic circuit diagrams','Logic'],['A1.3.1','Explain the role of an operating system','Operating Systems'],['A1.3.2','Explain memory, file, scheduling, security and interface management','Operating Systems'],['A1.3.3','Compare FCFS, round-robin, multilevel queue and priority scheduling','Operating Systems'],['A1.3.4','Evaluate polling and interrupt handling','Operating Systems'],['A1.3.5','Explain multitasking, resource allocation and deadlock','Operating Systems · HL'],['A1.3.6','Explain sensors, actuators and open- and closed-loop control','Control Systems · HL'],['A1.3.7','Apply control-system concepts to real-world situations','Control Systems · HL'],['A1.4.1','Evaluate compilers and interpreters, including JIT and bytecode','Translation · HL']],
    'A2 · Networks':[
      ['A2.1.1','Explain the purpose and characteristics of LANs, WANs, PANs and VPNs','Fundamentals'],['A2.1.2','Explain internet, cloud, distributed and edge-computing infrastructure','Infrastructure'],['A2.1.3','Explain the functions of gateways, routers, switches and NICs','Devices'],['A2.1.4','Explain TCP, UDP, HTTP, HTTPS and DHCP','Protocols'],['A2.1.5','Explain the four layers of the TCP/IP model','Protocols · HL'],['A2.2.1','Compare star, mesh and hybrid topologies','Architecture'],['A2.2.2','Explain DNS, DHCP, file, mail, proxy and web servers','Servers · HL'],['A2.2.3','Compare client–server and peer-to-peer networks','Architecture'],['A2.2.4','Explain segmentation, subnetting and VLANs','Architecture'],['A2.3.1','Distinguish IPv4/IPv6, public/private and static/dynamic addressing and NAT','Addressing'],['A2.3.2','Compare fibre-optic, coaxial and wireless transmission media','Transmission'],['A2.3.3','Explain packet switching','Transmission'],['A2.3.4','Compare static and dynamic routing','Routing · HL'],['A2.4.1','Discuss the effectiveness of firewalls','Security'],['A2.4.2','Explain DDoS, MitM, SQL injection and XSS vulnerabilities','Security · HL'],['A2.4.3','Evaluate MFA, IDS/IPS, TLS and VPN countermeasures','Security · HL'],['A2.4.4','Explain symmetric/asymmetric encryption and digital certificates','Security']],
    'A3 · Databases':[
      ['A3.1.1','Explain relational databases, primary keys, foreign keys and composite keys','Fundamentals'],['A3.2.1','Distinguish conceptual, logical and physical schemas','Design'],['A3.2.2','Construct ER diagrams using cardinality and modality','Design'],['A3.2.3','Select appropriate data types','Design'],['A3.2.4','Design relational tables','Design'],['A3.2.5','Normalize data to 1NF, 2NF and 3NF','Design'],['A3.2.6','Normalize a real-world scenario to 3NF','Design'],['A3.2.7','Evaluate the need for denormalization','Design'],['A3.3.1','Distinguish DDL and DML','SQL'],['A3.3.2','Write SELECT, JOIN, WHERE, GROUP BY and HAVING queries','SQL'],['A3.3.3','Modify data using INSERT, UPDATE and DELETE','SQL'],['A3.3.4','Use AVG, COUNT, MAX, MIN and SUM aggregate functions','SQL · HL'],['A3.3.5','Compare virtual and materialized database views','Database · HL'],['A3.3.6','Explain ACID transactions and BEGIN, COMMIT and ROLLBACK','Database · HL'],['A3.4.1','Compare NoSQL, cloud, spatial and in-memory databases','Alternative Databases · HL'],['A3.4.2','Explain data warehouses','Alternative Databases · HL'],['A3.4.3','Explain OLAP and data mining','Alternative Databases · HL'],['A3.4.4','Explain distributed databases','Alternative Databases · HL']],
    'A4 · Machine Learning':[
      ['A4.1.1','Compare supervised, unsupervised, reinforcement, deep and transfer learning','Machine Learning'],['A4.1.2','Explain GPU, TPU, FPGA, ASIC and HPC requirements','ML Hardware'],['A4.2.1','Apply data-cleaning techniques','Preprocessing · HL'],['A4.2.2','Apply feature-selection techniques','Preprocessing · HL'],['A4.2.3','Apply dimensionality-reduction techniques','Preprocessing · HL'],['A4.3.1','Explain and apply linear regression','Approaches · HL'],['A4.3.2','Explain K-nearest neighbours and decision trees','Approaches · HL'],['A4.3.3','Explain hyperparameter tuning, overfitting and underfitting','Approaches · HL'],['A4.3.4','Explain clustering','Approaches · HL'],['A4.3.5','Explain association-rule learning','Approaches · HL'],['A4.3.6','Explain reinforcement learning','Approaches · HL'],['A4.3.7','Explain genetic algorithms','Approaches · HL'],['A4.3.8','Explain perceptrons and multilayer perceptrons','ANN · HL'],['A4.3.9','Explain convolutional neural networks','ANN · HL'],['A4.3.10','Select and compare suitable machine-learning models','Machine Learning · HL'],['A4.4.1','Discuss bias, privacy and transparency in machine learning','Ethics'],['A4.4.2','Discuss the ethics of integrating AI into everyday life','Ethics']],
    'B1 · Computational Thinking':[
      ['B1.1.1','Write a clear problem specification','Problem Solving'],['B1.1.2','Explain abstraction, decomposition, pattern recognition and algorithm design','Computational Thinking'],['B1.1.3','Apply computational thinking to solve problems','Computational Thinking'],['B1.1.4','Trace flowcharts using standard symbols','Flowcharts']],
    'B2 · Programming':[
      ['B2.1.1','Use variables and appropriate data types','Fundamentals'],['B2.1.2','Manipulate strings and substrings','Fundamentals'],['B2.1.3','Apply exception handling and debugging techniques','Fundamentals'],['B2.2.1','Compare static and dynamic structures and use ArrayList','Data Structures'],['B2.2.2','Apply stack (LIFO) and queue (FIFO) operations','Data Structures'],['B2.3.1','Use sequence, selection and iteration constructs','Programming Constructs'],['B2.3.2','Use functions and modular design','Programming Constructs'],['B2.4.1','Analyse algorithm efficiency using Big O notation','Algorithms'],['B2.4.2','Implement linear and binary search','Algorithms'],['B2.4.3','Implement bubble sort and selection sort','Algorithms'],['B2.4.4','Explain recursion and apply it to quicksort','Algorithms · HL'],['B2.4.5','Write recursive algorithms','Algorithms · HL'],['B2.5.1','Read, write and append text files','File Processing']],
    'B3–B4 · OOP & Abstract Data Types':[
      ['B3.1.1','Evaluate OOP and construct UML class diagrams','OOP'],['B3.1.2','Define classes, create objects and distinguish static and instance members','OOP'],['B3.1.3','Apply encapsulation and access modifiers','OOP'],['B3.2.1','Apply inheritance and access control','OOP · HL'],['B3.2.2','Apply polymorphism through method overriding','OOP · HL'],['B3.2.3','Apply abstraction using abstract classes','OOP · HL'],['B3.2.4','Compare composition and aggregation','OOP · HL'],['B3.2.5','Explain Singleton, Factory and Observer patterns','Design Patterns · HL'],['B4.1.1','Explain the purpose and principles of abstract data types','ADT · HL'],['B4.1.2','Evaluate singly, doubly and circular linked lists','ADT · HL'],['B4.1.3','Implement linked-list insertion, deletion, search and traversal','ADT · HL'],['B4.1.4','Implement BST insertion, deletion, search and traversal','ADT · HL'],['B4.1.5','Apply set union, intersection and difference','ADT · HL'],['B4.1.6','Explain and use hash tables, maps and sets','ADT · HL']]
  }}
};

const DEFAULT_PRACTICE = [
  {date:'2025-07-03',subject:'math',name:'Day 21',topic:'Calculus & Sequences',score:69,notes:'Related rates formula error'},
  {date:'2025-07-03',subject:'math',name:'Day 22 re-sit',topic:'Mixed AAHL',score:90,notes:'Major improvement after re-sit'},
  {date:'2025-01-01',subject:'physics',name:'Pulley FBD',topic:'A2 Forces',score:68,notes:'Free-body diagram review'},
  {date:'2025-01-01',subject:'physics',name:'Uncertainty 1',topic:'Uncertainty',score:36,notes:'Absolute uncertainty'},
  {date:'2025-01-01',subject:'physics',name:'Uncertainty 4',topic:'Uncertainty',score:79,notes:'Improved after correction'},
  {date:'2025-01-01',subject:'physics',name:'Collision 1',topic:'A2 Momentum',score:38,notes:'Elastic vs inelastic'},
  {date:new Date().toISOString().slice(0,10),subject:'cs',name:'Network concepts',topic:'A2 Networks',score:76,notes:'Review subnetting'}
];

const KEY='ivan-ib-compass-v1';
const DEFAULT_CARDS=[
  {id:'card-1',subject:'physics',code:'A2.4',type:'Formula',tag:'Momentum',front:'Impulse와 momentum 변화의 관계는?',back:'J = FΔt = Δp = m(vf − vi)',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-2',subject:'math',code:'AHL 5.14',type:'Error',tag:'Integration',front:'Integration by parts의 공식과 가장 흔한 부호 실수는?',back:'∫u dv = uv − ∫v du\n특히 dv = sin x dx이면 v = −cos x.',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-3',subject:'cs',code:'A2.1.5',type:'Concept',tag:'Networks',front:'TCP/IP 모델의 4계층을 순서대로 설명하라.',back:'Application → Transport → Internet → Network Access',due:new Date().toISOString().slice(0,10),interval:0,reviews:0}
];
let data=loadData(); window.__ibData=data; let selectedSubject='physics'; let currentCardId=null; let answerVisible=false;let cloudClient=null,cloudUser=null,cloudSaveTimer=null,cloudLoading=false,activeWorkspace=null;
function staticObjectives(subjectKey){const s=SUBJECTS[subjectKey];return Object.entries(s.groups).flatMap(([group,items])=>items.map(item=>({group,code:item[0],title:item[1],category:item[2],level:(item[2]||'').includes('HL')?'HL only':'SL + HL',id:subjectKey+'-'+item[0],subject:subjectKey,custom:false})));}
function allObjectives(subjectKey){const d=window.__ibData||{},overrides=d.objectiveOverrides||{},archived=d.archivedObjectives||[];const base=staticObjectives(subjectKey).map(o=>Object.assign({},o,overrides[o.id]||{}));const custom=(d.customObjectives||[]).filter(o=>o.subject===subjectKey);return base.concat(custom).filter(o=>!archived.includes(o.id));}
function migrate(saved){saved.progress=saved.progress||{};saved.practice=saved.practice||[];saved.flashcards=saved.flashcards||JSON.parse(JSON.stringify(DEFAULT_CARDS));saved.customObjectives=saved.customObjectives||[];saved.objectiveOverrides=saved.objectiveOverrides||{};saved.archivedObjectives=saved.archivedObjectives||[];return saved}
function loadData(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)return migrate(saved)}catch(e){}const progress={};Object.keys(SUBJECTS).forEach((key,si)=>staticObjectives(key).forEach((o,i)=>{progress[o.id]={school:i<(si===0?15:si===1?8:10),status:i<(si===0?5:si===1?4:3)?'done':i<(si===0?9:si===1?7:6)?'progress':'todo',confidence:i<(si===0?5:si===1?4:3)?4:i<(si===0?9:si===1?7:6)?2:0}}));return migrate({progress,practice:DEFAULT_PRACTICE});}
function save(){window.__ibData=data;localStorage.setItem(KEY,JSON.stringify(data));queueCloudSave()}
function setSyncStatus(text,state){const el=document.querySelector('#syncStatus');if(!el)return;el.className='sync-status '+(state||'');el.innerHTML='<i></i> '+text}
function queueCloudSave(){if(!cloudClient||!cloudUser||cloudLoading)return;clearTimeout(cloudSaveTimer);setSyncStatus('동기화 중…','syncing');cloudSaveTimer=setTimeout(syncToCloud,650)}
async function syncToCloud(){if(!cloudClient||!cloudUser)return;const result=activeWorkspace?await cloudClient.from('workspace_data').upsert({workspace_id:activeWorkspace.workspace_id,payload:data,updated_at:new Date().toISOString()}):await cloudClient.from('user_data').upsert({user_id:cloudUser.id,payload:data,updated_at:new Date().toISOString()});if(result.error){setSyncStatus('동기화 오류','error');console.error(result.error)}else setSyncStatus(activeWorkspace?'가족 Workspace 저장됨':'클라우드 저장됨','online')}
async function refreshWorkspace(){activeWorkspace=null;if(!cloudClient||!cloudUser)return;const result=await cloudClient.rpc('get_my_workspace');if(!result.error&&result.data&&result.data.length)activeWorkspace=result.data[0];renderWorkspace();renderSyllabus()}
async function loadCloudData(){if(!cloudClient||!cloudUser)return;cloudLoading=true;setSyncStatus('클라우드 확인 중…','syncing');const result=activeWorkspace?await cloudClient.from('workspace_data').select('payload').eq('workspace_id',activeWorkspace.workspace_id).maybeSingle():await cloudClient.from('user_data').select('payload').eq('user_id',cloudUser.id).maybeSingle();if(result.error){setSyncStatus(activeWorkspace?'Workspace 설정 필요':'DB 설정 필요','error');cloudLoading=false;return}if(result.data&&result.data.payload&&Object.keys(result.data.payload).length){data=migrate(result.data.payload);window.__ibData=data;localStorage.setItem(KEY,JSON.stringify(data));renderAll();setSyncStatus(activeWorkspace?'가족 Workspace 연결됨':'클라우드 연결됨','online')}else{cloudLoading=false;await syncToCloud();setSyncStatus('첫 데이터 업로드됨','online');return}cloudLoading=false}
async function handleSession(session){cloudUser=session&&session.user?session.user:null;const button=document.querySelector('#accountButton');if(cloudUser){button.textContent=cloudUser.email||'계정';await refreshWorkspace();await loadCloudData()}else{activeWorkspace=null;button.textContent='로그인';setSyncStatus('이 기기에 저장됨','');renderWorkspace();renderSyllabus()}}
async function initCloud(){const cfg=window.IB_SUPABASE_CONFIG;if(!cfg||!window.supabase){setSyncStatus('오프라인 모드','error');return}cloudClient=window.supabase.createClient(cfg.url,cfg.publishableKey);const sessionResult=await cloudClient.auth.getSession();await handleSession(sessionResult.data.session);cloudClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(()=>handleSession(session),0)})}
function statusLabel(v){return {done:'✓ 완료',progress:'↻ 진행 중',todo:'○ 미완'}[v]}
function metrics(key){const list=allObjectives(key), states=list.map(o=>data.progress[o.id]||{}),done=states.filter(x=>x.status==='done').length,progress=states.filter(x=>x.status==='progress').length,gaps=list.filter(o=>isGap(o.id)).length;return{total:list.length,done,progress,gaps,pct:Math.round(done/list.length*100)}}
function isGap(id){const p=data.progress[id]||{};return p.school&&(p.status!=='done'||(+p.confidence||0)<3)}
function gapItems(){return Object.keys(SUBJECTS).flatMap(k=>allObjectives(k).filter(o=>isGap(o.id)).map(o=>({...o,subject:k})));}
function renderAll(){renderDashboard();renderSyllabus();renderPractice();renderFlashcards();renderFocus();}
function renderDashboard(){
  const all=Object.keys(SUBJECTS).map(metrics), total=all.reduce((n,m)=>n+m.total,0),done=all.reduce((n,m)=>n+m.done,0),pct=Math.round(done/total*100);document.querySelector('#overallMastery').textContent=pct+'%';
  document.querySelector('#subjectCards').innerHTML=Object.entries(SUBJECTS).map(([k,s])=>{const m=metrics(k);return `<button class="subject-card" data-subject-open="${k}" style="--accent:${s.color};--tint:${s.tint};text-align:left;color:inherit"><div class="subject-card-top"><span class="subject-icon">${s.icon}</span><small>${m.gaps} focus items</small></div><h3>${s.name}</h3><small>${m.done} of ${m.total} objectives mastered</small><div class="metric"><strong>${m.pct}%</strong><small>${m.progress} in progress</small></div><div class="progress-track"><i style="width:${m.pct}%"></i></div></button>`}).join('');
  const gaps=gapItems();document.querySelector('#gapBadge').textContent=gaps.length;document.querySelector('#priorityList').innerHTML=gaps.slice(0,4).map(o=>`<div class="priority-item"><span class="priority-code">${o.code}</span><span><b>${o.title}</b><small>${SUBJECTS[o.subject].name} · ${o.category}</small></span><span class="tag">Review</span></div>`).join('')||'<div class="empty">현재 우선 복습 항목이 없습니다.</div>';
  const recent=data.practice.slice(-7);document.querySelector('#scoreChart').innerHTML='<i class="target-line"></i>'+recent.map((p,i)=>`<div class="chart-bar" style="--score:${Math.max(4,p.score)}%" data-score="${p.score}%"><span>${p.name.slice(0,5)}</span></div>`).join('');
  const completedThisWeek=Math.min(15,done);document.querySelector('#weeklyTarget').textContent=`${completedThisWeek} / 15`;document.querySelector('#weeklyBar').style.width=Math.round(completedThisWeek/15*100)+'%';
}
function renderTabs(){document.querySelector('#subjectTabs').innerHTML=Object.entries(SUBJECTS).map(([k,s])=>`<button data-subject="${k}" class="${k===selectedSubject?'active':''}">${s.short}</button>`).join('')}
function renderSyllabus(){renderTabs();const searchEl=document.querySelector('#searchInput'),filterEl=document.querySelector('#statusFilter'),q=searchEl?searchEl.value.toLowerCase():'',filter=filterEl?filterEl.value:'all',m=metrics(selectedSubject),canManage=!activeWorkspace||activeWorkspace.member_role==='owner';document.querySelector('#addObjective').classList.toggle('owner-only-hidden',!canManage);document.querySelector('#syllabusSummary').innerHTML=`<div class="summary-metric"><strong>${m.total}</strong><span>전체 항목</span></div><div class="summary-metric"><strong>${m.done}</strong><span>완료</span></div><div class="summary-metric"><strong>${m.progress}</strong><span>진행 중</span></div><div class="summary-metric"><strong>${m.gaps}</strong><span>Focus gaps</span></div><div class="summary-metric"><strong>${m.pct}%</strong><span>Mastery</span></div>`;
  const grouped={};allObjectives(selectedSubject).forEach(o=>{if(!grouped[o.group])grouped[o.group]=[];grouped[o.group].push(o)});document.querySelector('#syllabusList').innerHTML=Object.entries(grouped).map(([group,items])=>{const objs=items.filter(o=>{const p=data.progress[o.id]||{status:'todo'};return(!q||(o.code+' '+o.title+' '+o.category).toLowerCase().includes(q))&&(filter==='all'||filter==='gap'&&isGap(o.id)||p.status===filter)});if(!objs.length)return'';return `<section class="syllabus-group"><button class="group-header"><span>${group}</span><small>${objs.length} objectives</small><span class="chevron">⌄</span></button><div class="objective-list">${objs.map(o=>{const p=data.progress[o.id]||{school:false,status:'todo',confidence:0};return `<div class="objective"><code>${o.code}</code><div class="objective-title"><div><b>${o.title}</b><small>${o.category}</small></div>${canManage?`<button class="objective-edit" data-edit-objective="${o.id}" title="항목 편집">✎</button>`:''}</div><button class="school-toggle ${p.school?'taught':''}" data-school="${o.id}">${p.school?'✓ 학교 완료':'학교 미진도'}</button><select class="status-select" data-status="${o.id}"><option value="todo" ${p.status==='todo'?'selected':''}>○ 미완</option><option value="progress" ${p.status==='progress'?'selected':''}>↻ 진행 중</option><option value="done" ${p.status==='done'?'selected':''}>✓ 완료</option></select><select class="confidence-select" data-confidence="${o.id}" aria-label="자신감"><option value="0" ${!p.confidence?'selected':''}>자신감 —</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${+p.confidence===n?'selected':''}>${'★'.repeat(n)} ${n}</option>`).join('')}</select><span class="gap-dot ${isGap(o.id)?'active':''}" title="${isGap(o.id)?'복습 필요':'Gap 없음'}"></span></div>`}).join('')}</div></section>`}).join('')||'<div class="empty">조건에 맞는 syllabus 항목이 없습니다.</div>'}
function renderPractice(){const scores=data.practice.map(p=>+p.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,atTarget=scores.filter(x=>x>=75).length,last=scores.length?scores[scores.length-1]:0;document.querySelector('#practiceStats').innerHTML=[['기록',data.practice.length,'#587b96'],['평균 점수',avg+'%','#bd6549'],['목표 달성',atTarget+'회','#d6a44f'],['최근 점수',last+'%','#204b40']].map(x=>`<div class="stat-card" style="--accent:${x[2]}"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');document.querySelector('#practiceTable').innerHTML=[...data.practice].reverse().map(p=>`<tr><td>${p.date}</td><td>${SUBJECTS[p.subject].name}</td><td><b>${p.name}</b></td><td>${p.topic||'—'}</td><td class="score-cell">${p.score}%</td><td>${p.notes||'—'}</td></tr>`).join('')}
function today(){return new Date().toISOString().slice(0,10)}
function dueCards(){return data.flashcards.filter(c=>(c.due||today())<=today())}
function renderFlashcards(){
  const due=dueCards(),mastered=data.flashcards.filter(c=>(c.interval||0)>=14).length,reviewed=data.flashcards.reduce((n,c)=>n+(c.reviews||0),0);document.querySelector('#cardBadge').textContent=due.length;
  document.querySelector('#flashcardStats').innerHTML=[['전체 카드',data.flashcards.length,'#587b96'],['오늘 복습',due.length,'#bd6549'],['장기 기억',mastered,'#d6a44f'],['누적 복습',reviewed,'#204b40']].map(x=>`<div class="stat-card" style="--accent:${x[2]}"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');
  if(!currentCardId||!data.flashcards.some(c=>c.id===currentCardId&&(c.due||today())<=today()))currentCardId=due.length?due[0].id:null;const card=data.flashcards.find(c=>c.id===currentCardId);
  document.querySelector('#reviewStage').innerHTML=!card?`<div class="review-empty"><span class="empty-icon">✓</span><h2>오늘 복습 완료!</h2><p>예정된 Flashcard를 모두 학습했습니다. 새 카드를 만들거나 내일 다시 확인하세요.</p><button class="primary" data-new-card>새 카드 만들기</button></div>`:`<div class="review-card"><div class="review-meta"><span>${SUBJECTS[card.subject].name}</span><span>${card.code||'No code'}</span><span>${card.type}</span></div><div class="flip-card" data-flip-card>${answerVisible?`<div class="answer">${escapeHtml(card.back)}</div><p>기억 정도를 선택하세요</p>`:`<h2>${escapeHtml(card.front)}</h2><p>카드를 눌러 정답 보기</p>`}</div>${answerVisible?`<div class="rating-buttons"><button data-rate="again">다시<br><small>오늘</small></button><button data-rate="hard">어려움<br><small>1일</small></button><button data-rate="good">보통<br><small>${nextInterval(card,'good')}일</small></button><button data-rate="easy">쉬움<br><small>${nextInterval(card,'easy')}일</small></button></div>`:''}</div>`;
  const filter=document.querySelector('#cardSubjectFilter').value;const cards=data.flashcards.filter(c=>filter==='all'||c.subject===filter);document.querySelector('#cardLibrary').innerHTML=cards.map(c=>`<div class="library-card"><span><b>${escapeHtml(c.front)}</b><small>${SUBJECTS[c.subject].short} · ${c.code||c.type} · <span class="${(c.due||today())<=today()?'due-pill':''}">${(c.due||today())<=today()?'오늘 복습':'다음 '+c.due}</span></small></span><button data-delete-card="${c.id}" title="카드 삭제">×</button></div>`).join('')||'<div class="empty">카드가 없습니다.</div>'
}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function nextInterval(card,rating){const current=card.interval||0;if(rating==='again')return 0;if(rating==='hard')return 1;if(rating==='easy')return current<1?4:Math.max(4,Math.round(current*2.5));return current<1?1:current<3?3:Math.round(current*2)}
function rateCard(rating){const card=data.flashcards.find(c=>c.id===currentCardId);if(!card)return;const days=nextInterval(card,rating);card.interval=days;card.reviews=(card.reviews||0)+1;const next=new Date();next.setDate(next.getDate()+days);card.due=next.toISOString().slice(0,10);answerVisible=false;currentCardId=null;save();renderAll();toast(days?'다음 복습: '+days+'일 후':'잠시 후 다시 보여드릴게요')}
function renderFocus(){const gaps=gapItems();document.querySelector('#focusGrid').innerHTML=gaps.map(o=>{const p=data.progress[o.id];return `<article class="focus-card"><div><code>${o.code} · ${SUBJECTS[o.subject].short}</code><h3>${o.title}</h3><p>${p.status==='progress'?'현재 학습 중':'학교 진도 완료 · Ivan 미완'} · 자신감 ${p.confidence||0}/5</p></div><button data-complete="${o.id}">완료로 표시</button></article>`}).join('')||'<div class="panel empty">멋집니다. 현재 학교 진도와 Ivan의 학습 사이에 Gap이 없습니다.</div>'}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function openDialog(){const f=document.querySelector('#practiceForm');f.reset();f.elements.date.value=new Date().toISOString().slice(0,10);document.querySelector('#practiceDialog').showModal()}
function openCardDialog(){document.querySelector('#flashcardForm').reset();document.querySelector('#flashcardDialog').showModal()}
function findObjective(id){return Object.keys(SUBJECTS).flatMap(k=>allObjectives(k)).find(o=>o.id===id)}
function renderWorkspace(){const current=document.querySelector('#workspaceCurrent'),setup=document.querySelector('#workspaceSetup');if(!current||!setup)return;if(!activeWorkspace){current.innerHTML='';setup.classList.remove('hidden');return}setup.classList.add('hidden');const owner=activeWorkspace.member_role==='owner';current.innerHTML=`<div class="workspace-info"><span class="role-chip">${owner?'Owner · 부모':'Student · Ivan'}</span><h3>${escapeHtml(activeWorkspace.workspace_name)}</h3><p>${owner?'Syllabus를 관리하고 학생을 초대할 수 있습니다.':'진도, Practice와 Flashcard가 가족 계정과 공유됩니다.'}</p>${owner?`<div class="invite-box"><span><small>IVAN 초대 코드</small><br><code>${activeWorkspace.invite_code}</code></span><button type="button" data-copy-invite>코드 복사</button></div>`:`<p class="student-note">Syllabus 구조 변경은 Owner 계정에서 관리합니다.</p>`}</div>`}
function openObjectiveDialog(id){if(activeWorkspace&&activeWorkspace.member_role!=='owner'){toast('Syllabus 편집은 Owner만 가능합니다');return}const f=document.querySelector('#objectiveForm');f.reset();const o=id?findObjective(id):null;f.elements.originalId.value=o?o.id:'';f.elements.subject.value=o?o.subject:selectedSubject;f.elements.subject.disabled=!!o;f.elements.code.value=o?o.code:'';f.elements.group.value=o?o.group:'';f.elements.title.value=o?o.title:'';f.elements.category.value=o?o.category:'';f.elements.level.value=o&&o.level?o.level:'SL + HL';document.querySelector('#objectiveDialogTitle').textContent=o?'항목 수정':'항목 추가';document.querySelector('#archiveObjective').classList.toggle('hidden',!o);document.querySelector('#objectiveDialog').showModal()}
document.addEventListener('click',e=>{
  const view=e.target.closest('[data-view]');if(view)switchView(view.dataset.view);
  const go=e.target.closest('[data-go]');if(go)switchView(go.dataset.go);
  const subject=e.target.closest('[data-subject]');if(subject){selectedSubject=subject.dataset.subject;renderSyllabus()}
  const open=e.target.closest('[data-subject-open]');if(open){selectedSubject=open.dataset.subjectOpen;renderSyllabus();switchView('syllabus')}
  const school=e.target.closest('[data-school]');if(school){data.progress[school.dataset.school].school=!data.progress[school.dataset.school].school;save();renderAll();toast('학교 진도를 업데이트했습니다')}
  const header=e.target.closest('.group-header');if(header)header.parentElement.classList.toggle('collapsed');
  const complete=e.target.closest('[data-complete]');if(complete){data.progress[complete.dataset.complete].status='done';data.progress[complete.dataset.complete].confidence=Math.max(3,data.progress[complete.dataset.complete].confidence||0);save();renderAll();toast('완료로 표시했습니다')}
  const edit=e.target.closest('[data-edit-objective]');if(edit)openObjectiveDialog(edit.dataset.editObjective);
  if(e.target.closest('[data-new-card]'))openCardDialog();
  if(e.target.closest('[data-flip-card]')){answerVisible=true;renderFlashcards()}
  const rate=e.target.closest('[data-rate]');if(rate)rateCard(rate.dataset.rate);
  const removeCard=e.target.closest('[data-delete-card]');if(removeCard&&confirm('이 Flashcard를 삭제할까요?')){data.flashcards=data.flashcards.filter(c=>c.id!==removeCard.dataset.deleteCard);save();renderAll();toast('카드를 삭제했습니다')}
  if(e.target.closest('[data-copy-invite]')&&activeWorkspace){navigator.clipboard.writeText(activeWorkspace.invite_code);toast('초대 코드를 복사했습니다')}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-status]')){const id=e.target.dataset.status;data.progress[id].status=e.target.value;if(e.target.value==='done'&&!data.progress[id].confidence)data.progress[id].confidence=3;save();renderAll();toast('학습 상태를 저장했습니다')}if(e.target.matches('[data-confidence]')){data.progress[e.target.dataset.confidence].confidence=+e.target.value;save();renderAll();toast('자신감을 저장했습니다')}});
document.querySelector('#searchInput').addEventListener('input',renderSyllabus);document.querySelector('#statusFilter').addEventListener('change',renderSyllabus);
document.querySelector('#quickAdd').addEventListener('click',openDialog);document.querySelector('#addPractice').addEventListener('click',openDialog);
document.querySelector('#addFlashcard').addEventListener('click',openCardDialog);document.querySelector('#addObjective').addEventListener('click',()=>openObjectiveDialog());
document.querySelector('#resetButton').addEventListener('click',()=>{if(confirm('저장된 변경사항을 지우고 샘플 상태로 되돌릴까요?')){localStorage.removeItem(KEY);data=loadData();save();renderAll();toast('샘플 데이터로 초기화했습니다')}});
const subjectSelect=document.querySelector('#practiceForm [name=subject]');subjectSelect.innerHTML=Object.entries(SUBJECTS).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('');
const subjectOptions=Object.entries(SUBJECTS).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('');document.querySelector('#flashcardForm [name=subject]').innerHTML=subjectOptions;document.querySelector('#objectiveForm [name=subject]').innerHTML=subjectOptions;document.querySelector('#cardSubjectFilter').innerHTML='<option value="all">모든 과목</option>'+subjectOptions;document.querySelector('#cardSubjectFilter').addEventListener('change',renderFlashcards);
document.querySelector('#savePractice').addEventListener('click',e=>{const f=document.querySelector('#practiceForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f);data.practice.push({date:fd.get('date'),subject:fd.get('subject'),name:fd.get('name'),topic:fd.get('topic'),score:+fd.get('score'),notes:fd.get('notes')});save();renderAll();toast('연습 기록을 저장했습니다')});
document.querySelector('#saveFlashcard').addEventListener('click',e=>{const f=document.querySelector('#flashcardForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f);data.flashcards.push({id:'card-'+Date.now(),subject:fd.get('subject'),code:fd.get('code'),type:fd.get('type'),tag:fd.get('tag'),front:fd.get('front'),back:fd.get('back'),due:today(),interval:0,reviews:0});currentCardId=null;save();renderAll();toast('Flashcard를 만들었습니다')});
document.querySelector('#saveObjective').addEventListener('click',e=>{const f=document.querySelector('#objectiveForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f),originalId=fd.get('originalId'),subject=f.elements.subject.value,values={subject,code:fd.get('code'),group:fd.get('group'),title:fd.get('title'),category:fd.get('category'),level:fd.get('level')};if(originalId){const custom=data.customObjectives.find(o=>o.id===originalId);if(custom)Object.assign(custom,values);else data.objectiveOverrides[originalId]=values}else{values.id=subject+'-custom-'+Date.now();values.custom=true;data.customObjectives.push(values);data.progress[values.id]={school:false,status:'todo',confidence:0}}save();renderAll();toast(originalId?'Syllabus 항목을 수정했습니다':'Syllabus 항목을 추가했습니다')});
document.querySelector('#archiveObjective').addEventListener('click',()=>{const id=document.querySelector('#objectiveForm').elements.originalId.value;if(id&&confirm('이 항목을 보관할까요? 기존 진도 기록은 유지됩니다.')){data.archivedObjectives.push(id);save();document.querySelector('#objectiveDialog').close();renderAll();toast('항목을 보관했습니다')}});
document.querySelector('#accountButton').addEventListener('click',()=>{if(cloudUser){renderWorkspace();document.querySelector('#workspaceError').textContent='';document.querySelector('#workspaceDialog').showModal()}else{document.querySelector('#authForm').reset();document.querySelector('#authError').textContent='';document.querySelector('#authDialog').showModal()}});
async function authenticate(mode){const form=document.querySelector('#authForm');if(!form.reportValidity())return;const email=form.elements.email.value.trim(),password=form.elements.password.value,errorEl=document.querySelector('#authError');errorEl.textContent='';if(!cloudClient){errorEl.textContent='Supabase에 연결할 수 없습니다.';return}const cfg=window.IB_SUPABASE_CONFIG||{};const result=mode==='signup'?await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:cfg.redirectUrl}}):await cloudClient.auth.signInWithPassword({email,password});if(result.error){errorEl.textContent=result.error.message;return}document.querySelector('#authDialog').close();if(mode==='signup'&&!result.data.session)toast('확인 이메일을 보냈습니다. 이메일 인증 후 로그인하세요.');else toast(mode==='signup'?'계정을 만들었습니다':'로그인했습니다')}
document.querySelector('#signUpButton').addEventListener('click',()=>authenticate('signup'));document.querySelector('#signInButton').addEventListener('click',()=>authenticate('signin'));
document.querySelector('#workspaceSignOut').addEventListener('click',async()=>{if(confirm('모든 기기에서 로그아웃할까요?')){document.querySelector('#workspaceDialog').close();await cloudClient.auth.signOut()}});
document.querySelector('#createWorkspace').addEventListener('click',async()=>{const form=document.querySelector('#workspaceForm'),name=form.elements.workspaceName.value.trim(),errorEl=document.querySelector('#workspaceError');errorEl.textContent='';if(!name){errorEl.textContent='Workspace 이름을 입력하세요.';return}const result=await cloudClient.rpc('create_family_workspace',{workspace_name:name});if(result.error){errorEl.textContent=result.error.message;return}await refreshWorkspace();await loadCloudData();renderWorkspace();toast('가족 Workspace를 만들었습니다')});
document.querySelector('#joinWorkspace').addEventListener('click',async()=>{const form=document.querySelector('#workspaceForm'),code=form.elements.inviteCode.value.trim().toUpperCase(),errorEl=document.querySelector('#workspaceError');errorEl.textContent='';if(code.length!==8){errorEl.textContent='8자리 초대 코드를 입력하세요.';return}const result=await cloudClient.rpc('join_family_workspace',{code});if(result.error){errorEl.textContent=result.error.message;return}await refreshWorkspace();await loadCloudData();renderWorkspace();toast('가족 Workspace에 참여했습니다')});
document.querySelector('#todayLabel').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js');
renderAll();
initCloud();
