const APP_VERSION='36';
const SUBJECTS = {
  physics: { name:'Physics HL', short:'Physics', icon:'φ', color:'#587b96', tint:'#dfe9ee', groups:{
    'A · Space, Time & Motion':[
      ['A1','Kinematics','SL + HL'],['A2','Forces and momentum','SL + HL'],['A3','Work, energy and power','SL + HL'],['A4','Rigid body mechanics','HL only'],['A5','Galilean and special relativity','HL only']],
    'B · Particulate Nature of Matter':[
      ['B1','Thermal energy transfers','SL + HL'],['B2','Greenhouse effect','SL + HL'],['B3','Gas laws','SL + HL'],['B4','Thermodynamics','HL only'],['B5','Current and circuits','SL + HL']],
    'C · Wave Behaviour':[
      ['C1','Simple harmonic motion','SL + HL · HL additional'],['C2','Wave model','SL + HL'],['C3','Wave phenomena','SL + HL · HL additional'],['C4','Standing waves and resonance','SL + HL'],['C5','Doppler effect','SL + HL · HL additional']],
    'D · Fields':[
      ['D1','Gravitational fields','SL + HL · HL additional'],['D2','Electric and magnetic fields','SL + HL · HL additional'],['D3','Motion in electromagnetic fields','SL + HL'],['D4','Induction','HL only']],
    'E · Nuclear & Quantum Physics':[
      ['E1','Structure of the atom','SL + HL · HL additional'],['E2','Quantum physics','HL only'],['E3','Radioactive decay','SL + HL · HL additional'],['E4','Fission','SL + HL'],['E5','Fusion and stars','SL + HL']],
    'Experimental programme':[
      ['XP1','Measurement, uncertainties and data processing','Skills'],['XP2','Practical work and experimental design','Skills'],['XP3','Scientific investigation','Assessment']]
  }},
  math: { name:'Math AA HL', short:'Mathematics', icon:'∑', color:'#bd6549', tint:'#f2ded7', groups:{
    'Topic 1 · Number & Algebra':[
      ['SL 1.1','Scientific notation','Algebra'],['SL 1.2','Arithmetic sequences and series','Sequences'],['SL 1.3','Geometric sequences and series','Sequences'],['SL 1.4','Financial applications','Finance'],['SL 1.5','Laws of exponents and logarithms','Algebra'],['SL 1.6','Simple deductive proof','Proof'],['SL 1.7','Solving exponential equations','Algebra'],['SL 1.8','Infinite convergent geometric series','Sequences'],['SL 1.9','Binomial theorem','Algebra'],['AHL 1.10','Counting principles and generalized binomial theorem','Algebra · HL'],['AHL 1.11','Partial fractions','Algebra · HL'],['AHL 1.12','Complex numbers in Cartesian form and the Argand plane','Complex numbers · HL'],['AHL 1.13','Polar and Euler forms of complex numbers','Complex numbers · HL'],['AHL 1.14','Complex roots and De Moivre’s theorem','Complex numbers · HL'],['AHL 1.15','Proof by induction, contradiction and counterexample','Proof · HL'],['AHL 1.16','Systems of linear equations','Algebra · HL']],
    'Topic 2 · Functions':[
      ['SL 2.1','Straight lines; parallel and perpendicular','Functions'],['SL 2.2','Domain, range and inverse','Functions'],['SL 2.3','Graph sketching with technology','Functions'],['SL 2.4','Key features of graphs','Functions'],['SL 2.5','Composite and inverse functions','Functions'],['SL 2.6','Quadratic functions and graphs','Functions'],['SL 2.7','Quadratic equations and inequalities','Functions'],['SL 2.8','Rational functions and asymptotes','Functions'],['SL 2.9','Exponential and logarithmic functions','Functions'],['SL 2.10','Solving equations graphically and analytically','Functions'],['SL 2.11','Transformations of graphs','Functions'],['AHL 2.12',"Polynomials, Vieta's formulas",'Functions · HL'],['AHL 2.13','Advanced rational functions','Functions · HL'],['AHL 2.14','Odd/even functions and domain restriction','Functions · HL'],['AHL 2.15','Functional inequalities','Functions · HL'],['AHL 2.16','Absolute value and reciprocal graphs','Functions · HL']],
    'Topic 3 · Geometry & Trigonometry':[
      ['SL 3.1','Three-dimensional geometry, surface area and volume','Geometry'],['SL 3.2','Sine rule, cosine rule and triangle area','Trigonometry'],['SL 3.3','Applications and bearings','Trigonometry'],['SL 3.4','Radian measure, arc length and sector area','Trigonometry'],['SL 3.5','Unit circle, exact values and ambiguous case','Trigonometry'],['SL 3.6','Pythagorean and double-angle identities','Trigonometry'],['SL 3.7','Circular functions, graphs and transformations','Trigonometry'],['SL 3.8','Trigonometric equations in a finite interval','Trigonometry'],['AHL 3.9','Reciprocal and inverse trigonometric functions','Trigonometry · HL'],['AHL 3.10','Compound-angle and double-angle identities','Trigonometry · HL'],['AHL 3.11','Symmetries of trigonometric functions','Trigonometry · HL'],['AHL 3.12','Vectors in two and three dimensions','Vectors · HL'],['AHL 3.13','Scalar product and angles between vectors','Vectors · HL'],['AHL 3.14','Vector equations of lines','Vectors · HL'],['AHL 3.15','Coincident, parallel, intersecting and skew lines','Vectors · HL'],['AHL 3.16','Vector product and geometric applications','Vectors · HL'],['AHL 3.17','Vector and Cartesian equations of planes','Vectors · HL'],['AHL 3.18','Intersections and angles involving lines and planes','Vectors · HL']],
    'Topic 4 · Statistics & Probability':[
      ['SL 4.1','Population, sampling, bias and outliers','Statistics'],['SL 4.2','Frequency tables, histograms and box plots','Statistics'],['SL 4.3','Measures of central tendency and dispersion','Statistics'],['SL 4.4','Correlation and regression of y on x','Statistics'],['SL 4.5','Trials, outcomes, events and expected occurrences','Probability'],['SL 4.6','Combined, conditional and independent events','Probability'],['SL 4.7','Discrete random variables and expected value','Probability'],['SL 4.8','Binomial distribution','Probability'],['SL 4.9','Normal distribution','Probability'],['SL 4.10','Regression of x on y','Statistics'],['SL 4.11','Conditional probability and independence','Probability'],['SL 4.12','Standardized normal variables','Probability'],['AHL 4.13','Bayes’ theorem','Probability · HL'],['AHL 4.14','Discrete and continuous random variables','Probability · HL']],
    'Topic 5 · Calculus':[
      ['SL 5.1','Limits, gradients and rates of change','Calculus'],['SL 5.2','Increasing and decreasing functions','Calculus'],['SL 5.3','Derivatives of polynomials','Calculus'],['SL 5.4','Tangents, normals and derivative interpretation','Calculus'],['SL 5.5','Definite integration with technology and area','Calculus'],['SL 5.6','Chain, product and quotient rules','Calculus'],['SL 5.7','Second derivatives and graph behaviour','Calculus'],['SL 5.8','Optimization and points of inflexion','Calculus'],['SL 5.9','Kinematics with calculus','Calculus'],['SL 5.10','Indefinite integration and substitution','Calculus'],['SL 5.11','Definite integrals and areas between curves','Calculus'],['AHL 5.12','Continuity, limits and derivatives from first principles','Calculus · HL'],['AHL 5.13','Limits and l’Hôpital’s rule','Calculus · HL'],['AHL 5.14','Implicit differentiation and related rates','Calculus · HL'],['AHL 5.15','Advanced derivatives and antiderivatives','Calculus · HL'],['AHL 5.16','Integration by substitution and by parts','Calculus · HL'],['AHL 5.17','Areas with the y-axis and volumes of revolution','Calculus · HL'],['AHL 5.18','First-order differential equations and Euler’s method','Calculus · HL'],['AHL 5.19','Maclaurin series','Calculus · HL']]
  }},
  cs: { name:'Computer Science HL', short:'Computer Science', icon:'⌘', color:'#d6a44f', tint:'#f2e8c9', groups:{
    'A1 · Computer Fundamentals':[
      ['A1.1.1','Explain CPU components: ALU, CU, registers and buses','Hardware'],['A1.1.2','Explain the role of a GPU','Hardware'],['A1.1.3','Compare CPU and GPU architecture and use cases','Hardware · HL'],['A1.1.4','Explain the purpose of RAM, ROM, cache and registers','Memory'],['A1.1.5','Explain the fetch–decode–execute cycle','CPU'],['A1.1.6','Explain instruction pipelining','CPU · HL'],['A1.1.7','Compare secondary storage technologies','Storage'],['A1.1.8','Explain lossy and lossless compression, RLE and transform coding','Data'],['A1.1.9','Distinguish SaaS, PaaS and IaaS','Cloud'],['A1.2.1','Convert and represent data in binary and hexadecimal','Representation'],['A1.2.2','Explain how integers, text, images, audio and video are stored','Representation'],['A1.2.3','Explain the purpose and use of logic gates','Logic'],['A1.2.4','Construct truth tables and simplify expressions using K-maps','Logic'],['A1.2.5','Construct logic circuit diagrams','Logic'],['A1.3.1','Explain the role of an operating system','Operating Systems'],['A1.3.2','Explain memory, file, scheduling, security and interface management','Operating Systems'],['A1.3.3','Compare FCFS, round-robin, multilevel queue and priority scheduling','Operating Systems'],['A1.3.4','Evaluate polling and interrupt handling','Operating Systems'],['A1.3.5','Explain multitasking, resource allocation and deadlock','Operating Systems · HL'],['A1.3.6','Explain sensors, actuators and open- and closed-loop control','Control Systems · HL'],['A1.3.7','Apply control-system concepts to real-world situations','Control Systems · HL'],['A1.4.1','Evaluate compilers and interpreters, including JIT and bytecode','Translation · HL']],
    'A2 · Networks':[
      ['A2.1.1','Explain the purpose and characteristics of LANs, WANs, PANs and VPNs','Fundamentals'],['A2.1.2','Explain internet, cloud, distributed and edge-computing infrastructure','Infrastructure'],['A2.1.3','Explain the functions of gateways, routers, switches and NICs','Devices'],['A2.1.4','Explain TCP, UDP, HTTP, HTTPS and DHCP','Protocols'],['A2.1.5','Explain the four layers of the TCP/IP model','Protocols · HL'],['A2.2.1','Compare star, mesh and hybrid topologies','Architecture'],['A2.2.2','Explain DNS, DHCP, file, mail, proxy and web servers','Servers · HL'],['A2.2.3','Compare client–server and peer-to-peer networks','Architecture'],['A2.2.4','Explain segmentation, subnetting and VLANs','Architecture'],['A2.3.1','Distinguish IPv4/IPv6, public/private and static/dynamic addressing and NAT','Addressing'],['A2.3.2','Compare fibre-optic, coaxial and wireless transmission media','Transmission'],['A2.3.3','Explain packet switching','Transmission'],['A2.3.4','Compare static and dynamic routing','Routing · HL'],['A2.4.1','Discuss the effectiveness of firewalls','Security'],['A2.4.2','Explain DDoS, MitM, SQL injection and XSS vulnerabilities','Security · HL'],['A2.4.3','Evaluate MFA, IDS/IPS, TLS and VPN countermeasures','Security · HL'],['A2.4.4','Explain symmetric/asymmetric encryption and digital certificates','Security']],
    'A3 · Databases':[
      ['A3.1.1','Explain relational databases, primary keys, foreign keys and composite keys','Fundamentals'],['A3.2.1','Distinguish conceptual, logical and physical schemas','Design'],['A3.2.2','Construct ER diagrams using cardinality and modality','Design'],['A3.2.3','Select appropriate data types','Design'],['A3.2.4','Design relational tables','Design'],['A3.2.5','Normalize data to 1NF, 2NF and 3NF','Design'],['A3.2.6','Normalize a real-world scenario to 3NF','Design'],['A3.2.7','Evaluate the need for denormalization','Design'],['A3.3.1','Distinguish DDL and DML','SQL'],['A3.3.2','Write SELECT, JOIN, WHERE, GROUP BY and HAVING queries','SQL'],['A3.3.3','Modify data using INSERT, UPDATE and DELETE','SQL'],['A3.3.4','Use AVG, COUNT, MAX, MIN and SUM aggregate functions','SQL · HL'],['A3.3.5','Compare virtual and materialized database views','Database · HL'],['A3.3.6','Explain ACID transactions and BEGIN, COMMIT and ROLLBACK','Database · HL'],['A3.4.1','Compare NoSQL, cloud, spatial and in-memory databases','Alternative Databases · HL'],['A3.4.2','Explain data warehouses','Alternative Databases · HL'],['A3.4.3','Explain OLAP and data mining','Alternative Databases · HL'],['A3.4.4','Explain distributed databases','Alternative Databases · HL']],
    'A4 · Machine Learning':[
      ['A4.1.1','Compare supervised, unsupervised, reinforcement, deep and transfer learning','Machine Learning'],['A4.1.2','Explain GPU, TPU, FPGA, ASIC and HPC requirements','ML Hardware'],['A4.2.1','Apply data-cleaning techniques','Preprocessing · HL'],['A4.2.2','Apply feature-selection techniques','Preprocessing · HL'],['A4.2.3','Apply dimensionality-reduction techniques','Preprocessing · HL'],['A4.3.1','Explain and apply linear regression','Approaches · HL'],['A4.3.2','Explain K-nearest neighbours and decision trees','Approaches · HL'],['A4.3.3','Explain hyperparameter tuning, overfitting and underfitting','Approaches · HL'],['A4.3.4','Explain clustering','Approaches · HL'],['A4.3.5','Explain association-rule learning','Approaches · HL'],['A4.3.6','Explain reinforcement learning','Approaches · HL'],['A4.3.7','Explain genetic algorithms','Approaches · HL'],['A4.3.8','Explain perceptrons and multilayer perceptrons','ANN · HL'],['A4.3.9','Explain convolutional neural networks','ANN · HL'],['A4.3.10','Select and compare suitable machine-learning models','Machine Learning · HL'],['A4.4.1','Discuss bias, privacy and transparency in machine learning','Ethics'],['A4.4.2','Discuss the ethics of integrating AI into everyday life','Ethics']],
    'B1 · Computational Thinking':[
      ['B1.1.1','Write a clear problem specification','Problem Solving'],['B1.1.2','Explain abstraction, decomposition, pattern recognition and algorithm design','Computational Thinking'],['B1.1.3','Apply computational thinking to solve problems','Computational Thinking'],['B1.1.4','Trace flowcharts using standard symbols','Flowcharts']],
    'B2 · Programming':[
      ['B2.1.1','Use variables and appropriate data types','Fundamentals'],['B2.1.2','Manipulate strings and substrings','Fundamentals'],['B2.1.3','Apply exception handling and debugging techniques','Fundamentals'],['B2.2.1','Compare static and dynamic structures and use ArrayList','Data Structures'],['B2.2.2','Apply stack (LIFO) and queue (FIFO) operations','Data Structures'],['B2.3.1','Use sequence, selection and iteration constructs','Programming Constructs'],['B2.3.2','Use functions and modular design','Programming Constructs'],['B2.4.1','Analyse algorithm efficiency using Big O notation','Algorithms'],['B2.4.2','Implement linear and binary search','Algorithms'],['B2.4.3','Implement bubble sort and selection sort','Algorithms'],['B2.4.4','Explain recursion and apply it to quicksort','Algorithms · HL'],['B2.4.5','Write recursive algorithms','Algorithms · HL'],['B2.5.1','Read, write and append text files','File Processing']],
    'B3–B4 · OOP & Abstract Data Types':[
      ['B3.1.1','Evaluate OOP and construct UML class diagrams','OOP'],['B3.1.2','Define classes, create objects and distinguish static and instance members','OOP'],['B3.1.3','Apply encapsulation and access modifiers','OOP'],['B3.2.1','Apply inheritance and access control','OOP · HL'],['B3.2.2','Apply polymorphism through method overriding','OOP · HL'],['B3.2.3','Apply abstraction using abstract classes','OOP · HL'],['B3.2.4','Compare composition and aggregation','OOP · HL'],['B3.2.5','Explain Singleton, Factory and Observer patterns','Design Patterns · HL'],['B4.1.1','Explain the purpose and principles of abstract data types','ADT · HL'],['B4.1.2','Evaluate singly, doubly and circular linked lists','ADT · HL'],['B4.1.3','Implement linked-list insertion, deletion, search and traversal','ADT · HL'],['B4.1.4','Implement BST insertion, deletion, search and traversal','ADT · HL'],['B4.1.5','Apply set union, intersection and difference','ADT · HL'],['B4.1.6','Explain and use hash tables, maps and sets','ADT · HL']]
  }}
};

const DEFAULT_PRACTICE = [
  {date:'2025-07-03',subject:'math',name:'Day 21',topic:'Calculus & Sequences',score:69,notes:'Related rates formula error'},
  {date:'2025-07-03',subject:'math',name:'Day 22 re-sit',topic:'Mixed AAHL',score:90,notes:'Major improvement after re-sit'},
  {date:'2025-01-01',subject:'physics',name:'Pulley FBD',topic:'A2 Forces',score:68,notes:'Free-body diagram review'},
  {date:'2025-01-01',subject:'physics',name:'Uncertainty 1',topic:'Uncertainty',score:36,notes:'Absolute uncertainty'},
  {date:'2025-01-01',subject:'physics',name:'Uncertainty 4',topic:'Uncertainty',score:79,notes:'Improved after correction'},
  {date:'2025-01-01',subject:'physics',name:'Collision 1',topic:'A2 Momentum',score:38,notes:'Elastic vs inelastic'},
  {date:new Date().toISOString().slice(0,10),subject:'cs',name:'Network concepts',topic:'A2 Networks',score:76,notes:'Review subnetting'}
  ,{date:'2025-07-05',subject:'math',name:'Day 25 · Mixed AAHL',topic:'Topics 1, 2, 3 & 5',score:52,notes:'28/54 · T1 77%, T2 30%, T3 67%, T5 41%'}
];

const KEY='ivan-ib-compass-v1';
const DEFAULT_CARDS=[
  {id:'card-1',subject:'physics',code:'A2.4',type:'Formula',tag:'Momentum',front:'Impulse와 momentum 변화의 관계는?',back:'J = FΔt = Δp = m(vf − vi)',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-2',subject:'math',code:'AHL 5.14',type:'Error',tag:'Integration',front:'Integration by parts의 공식과 가장 흔한 부호 실수는?',back:'∫u dv = uv − ∫v du\n특히 dv = sin x dx이면 v = −cos x.',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-3',subject:'cs',code:'A2.1.5',type:'Concept',tag:'Networks',front:'TCP/IP 모델의 4계층을 순서대로 설명하라.',back:'Application → Transport → Internet → Network Access',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-binomial-general-term',subject:'math',code:'AHL 1.10',type:'Formula',tag:'Binomial theorem',front:'Binomial theorem의 general term, 즉 “Large T” 공식은?',back:'General term:\n\nT(r+1) = C(n,r) × a^(n-r) × b^r\n\nC(n,r) = nCr\n\n주의: r번째 항이 아니라 (r+1)번째 항이다.',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-contradiction-rational-assumption',subject:'math',code:'AHL 1.15',type:'Proof',tag:'Contradiction',front:'√5가 rational이라고 가정할 때 반드시 써야 하는 3가지 조건은?',back:'Assume √5 is rational.\n\nThen √5 = a/b,\nwhere a, b ∈ Z,\nand gcd(a,b) = 1.\n\n핵심: fraction은 반드시 lowest terms로 둔다.',due:new Date().toISOString().slice(0,10),interval:0,reviews:0},
  {id:'card-limit-xlnx-lhopital',subject:'math',code:'AHL 5.13',type:'Error',tag:"L'Hôpital",front:'lim x→0⁺ x ln x 에서 L’Hôpital을 쓰기 전 반드시 어떻게 변형해야 하나?',back:'x ln x = ln x / x^(-1)\n\nThis gives (-∞)/(+∞), so L’Hôpital applies.\n\nAfter differentiating:\n(1/x) / (-1/x^2) = -x\n\nTherefore lim x→0⁺ x ln x = 0.\n\nIvan trap: (1/x)/(-1/x^2) is not 1/0. Convert the complex fraction by multiplying by the reciprocal.',due:new Date().toISOString().slice(0,10),interval:0,reviews:0}
];
let data=loadData(); window.__ibData=data; let selectedSubject='physics'; let currentCardId=null; let answerVisible=false;let cloudClient=null,cloudUser=null,cloudSaveTimer=null,cloudLoading=false,activeWorkspace=null;
function staticObjectives(subjectKey){const s=SUBJECTS[subjectKey];return Object.entries(s.groups).flatMap(([group,items])=>items.map(item=>({group,code:item[0],title:item[1],category:item[2],level:(item[2]||'').includes('HL')?'HL only':'SL + HL',id:subjectKey+'-'+item[0],subject:subjectKey,custom:false})));}
function allObjectives(subjectKey){const d=window.__ibData||{},overrides=d.objectiveOverrides||{},archived=d.archivedObjectives||[];const base=staticObjectives(subjectKey).map(o=>Object.assign({},o,overrides[o.id]||{}));const custom=(d.customObjectives||[]).filter(o=>o.subject===subjectKey);return base.concat(custom).filter(o=>!archived.includes(o.id));}
function migratePhysicsProgress(progress){const map={'physics-A1':['physics-A1.1','physics-A1.2','physics-A1.3','physics-A1.4'],'physics-A2':['physics-A2.1','physics-A2.2','physics-A2.3','physics-A2.4','physics-A2.5','physics-A2.6'],'physics-A3':['physics-A3.1','physics-A3.2'],'physics-A4':['physics-A4.1','physics-A4.2'],'physics-A5':['physics-A5.1'],'physics-B1':['physics-B1.1','physics-B1.2'],'physics-B2':['physics-B2.1'],'physics-B3':['physics-B3.1'],'physics-B4':['physics-B4.1'],'physics-B5':['physics-B5.1','physics-D5.1'],'physics-C1':['physics-C1.1','physics-C1.2'],'physics-C2':['physics-C2.1','physics-C2.2'],'physics-C3':['physics-C3.1'],'physics-C4':['physics-C5.1'],'physics-C5':['physics-C4.1'],'physics-D1':['physics-D1.1'],'physics-D2':['physics-D2.1'],'physics-D3':['physics-D3.1'],'physics-D4':['physics-D4.1'],'physics-E1':['physics-E1.1'],'physics-E2':['physics-E2.1'],'physics-E3':['physics-E3.1'],'physics-E4':['physics-E4.1'],'physics-E5':['physics-E5.1'],'physics-XP1':['physics-Uncertainty','physics-Measurement']};Object.entries(map).forEach(([next,olds])=>{if(progress[next])return;const states=olds.map(id=>progress[id]).filter(Boolean);if(!states.length)return;const confidence=Math.max(...states.map(s=>+s.confidence||0));const school=states.some(s=>s.school);const status=states.every(s=>s.status==='done')?'done':states.some(s=>s.status==='done'||s.status==='progress')?'progress':'todo';progress[next]={school,status,confidence}})}
function migrate(saved){
  saved.progress=saved.progress||{};saved.practice=saved.practice||[];
  migratePhysicsProgress(saved.progress);
  if(!saved.practice.some(p=>p.name==='Day 25 · Mixed AAHL'))saved.practice.push({date:'2025-07-05',subject:'math',name:'Day 25 · Mixed AAHL',topic:'Topics 1, 2, 3 & 5',score:52,notes:'28/54 · T1 77%, T2 30%, T3 67%, T5 41%'});
  if(!saved.practice.some(p=>p.name==='Annuity Drill'))saved.practice.push({date:'2026-07-08',subject:'math',name:'Annuity Drill',topic:'SL 1.4 Financial applications',score:89,notes:'32/36 · GP sum strong; review periodic-rate setup, exact annual R, threshold year checks'});
  if(!saved.practice.some(p=>p.name==='Projectile, impulse & 2D collision'))saved.practice.push({date:'2026-07-08',subject:'physics',name:'Projectile, impulse & 2D collision',topic:'A1 Kinematics, A2 Forces and momentum, XP1 Uncertainty',score:52,notes:'14/27 · A1 projectile 12/14 strong; A2 impulse/collision 1/12 major focus; XP1 MCQ 1/1'});
  if(!saved.practice.some(p=>p.name==='Day 27 · Mixed AAHL'))saved.practice.push({date:'2026-07-09',subject:'math',name:'Day 27 · Mixed AAHL',topic:'Proof, binomial, integration, related rates, trig',score:73,notes:'32/44 · induction 7/8; binomial 6/10; integration 8/10; related rates 4/8; trig 7/8'});
  if(!saved.practice.some(p=>p.name==='Day 28 · Mixed AAHL'))saved.practice.push({date:'2026-07-09',subject:'math',name:'Day 28 · Mixed AAHL',topic:'Proof, sequences, functions, trig, calculus, binomial, Vieta',score:77,notes:'46/60 · contradiction 3/6; sequences 7/8; functions 8/9; trig 7/8; implicit 6/8; integration 9/10; binomial 4/7; Vieta 2/4'});
  if(!saved.practice.some(p=>p.name==='Day 29 · Mixed AAHL'))saved.practice.push({date:'2026-07-11',subject:'math',name:'Day 29 · Mixed AAHL',topic:'Contradiction, rational functions, odd/even, inverse trig, absolute value',score:72,notes:'36/50 · contradiction 4/7; rational functions 5/10; odd/even inequality 8/10; inverse trig 12/14; absolute value 7/9'});
  const finance=saved.progress['math-SL 1.4']||{};
  saved.progress['math-SL 1.4']=Object.assign({},finance,{school:true,status:'done',confidence:Math.max(+finance.confidence||0,4)});
  saved.progress['math-AHL 1.15']=Object.assign({},saved.progress['math-AHL 1.15']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-AHL 1.10']=Object.assign({},saved.progress['math-AHL 1.10']||{},{school:true,status:'progress',confidence:2});
  saved.progress['math-AHL 5.16']=Object.assign({},saved.progress['math-AHL 5.16']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-AHL 5.14']=Object.assign({},saved.progress['math-AHL 5.14']||{},{school:true,status:'progress',confidence:1});
  saved.progress['math-AHL 3.10']=Object.assign({},saved.progress['math-AHL 3.10']||{},{school:true,status:'done',confidence:3});
  saved.progress['math-SL 1.2']=Object.assign({},saved.progress['math-SL 1.2']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-SL 2.5']=Object.assign({},saved.progress['math-SL 2.5']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-SL 2.8']=Object.assign({},saved.progress['math-SL 2.8']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-AHL 2.12']=Object.assign({},saved.progress['math-AHL 2.12']||{},{school:true,status:'progress',confidence:2});
  saved.progress['math-AHL 2.14']=Object.assign({},saved.progress['math-AHL 2.14']||{},{school:true,status:'progress',confidence:3});
  saved.progress['math-AHL 2.15']=Object.assign({},saved.progress['math-AHL 2.15']||{},{school:true,status:'progress',confidence:2});
  saved.progress['math-AHL 3.9']=Object.assign({},saved.progress['math-AHL 3.9']||{},{school:true,status:'done',confidence:4});
  saved.progress['math-AHL 2.16']=Object.assign({},saved.progress['math-AHL 2.16']||{},{school:true,status:'progress',confidence:3});
  saved.progress['physics-A1']=Object.assign({},saved.progress['physics-A1']||{},{school:true,status:'done',confidence:4});
  saved.progress['physics-A2']=Object.assign({},saved.progress['physics-A2']||{},{school:true,status:'progress',confidence:1});
  saved.progress['physics-XP1']=Object.assign({},saved.progress['physics-XP1']||{},{school:true,status:'progress',confidence:2});
  saved.flashcards=saved.flashcards||JSON.parse(JSON.stringify(DEFAULT_CARDS));const binomialCard=JSON.parse(JSON.stringify(DEFAULT_CARDS.find(c=>c.id==='card-binomial-general-term')));let updatedBinomialCard=false;saved.flashcards.forEach(c=>{const text=((c.front||'')+' '+(c.back||'')+' '+(c.tag||'')).toLowerCase();if(c.id==='card-binomial-general-term'||text.includes('large t')||text.includes('general term')||text.includes('t_{r+1}')||text.includes('binom(n,r)')){Object.assign(c,{id:'card-binomial-general-term',subject:binomialCard.subject,code:binomialCard.code,type:binomialCard.type,tag:binomialCard.tag,front:binomialCard.front,back:binomialCard.back});updatedBinomialCard=true}});if(!updatedBinomialCard)saved.flashcards.push(binomialCard);['card-contradiction-rational-assumption','card-limit-xlnx-lhopital'].forEach(id=>{const defaultCard=JSON.parse(JSON.stringify(DEFAULT_CARDS.find(c=>c.id===id)));if(defaultCard&&!saved.flashcards.some(c=>c.id===id))saved.flashcards.push(defaultCard)});saved.flashcards=saved.flashcards.filter((c,i,a)=>['card-binomial-general-term','card-contradiction-rational-assumption','card-limit-xlnx-lhopital'].includes(c.id)?a.findIndex(x=>x.id===c.id)===i:true);saved.customObjectives=saved.customObjectives||[];saved.objectiveOverrides=saved.objectiveOverrides||{};saved.archivedObjectives=saved.archivedObjectives||[];return saved}
function loadData(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)return migrate(saved)}catch(e){}const progress={};Object.keys(SUBJECTS).forEach((key,si)=>staticObjectives(key).forEach((o,i)=>{progress[o.id]={school:i<(si===0?15:si===1?8:10),status:i<(si===0?5:si===1?4:3)?'done':i<(si===0?9:si===1?7:6)?'progress':'todo',confidence:i<(si===0?5:si===1?4:3)?4:i<(si===0?9:si===1?7:6)?2:0}}));return migrate({progress,practice:DEFAULT_PRACTICE});}
function save(){window.__ibData=data;localStorage.setItem(KEY,JSON.stringify(data));queueCloudSave()}
function setSyncStatus(text,state){const el=document.querySelector('#syncStatus');if(!el)return;el.className='sync-status '+(state||'');el.innerHTML='<i></i> '+text}
function queueCloudSave(){if(!cloudClient||!cloudUser||cloudLoading)return;clearTimeout(cloudSaveTimer);setSyncStatus('동기화 중…','syncing');cloudSaveTimer=setTimeout(syncToCloud,650)}
async function syncToCloud(){if(!cloudClient||!cloudUser)return;const result=activeWorkspace?await cloudClient.from('workspace_data').upsert({workspace_id:activeWorkspace.workspace_id,payload:data,updated_at:new Date().toISOString()}):await cloudClient.from('user_data').upsert({user_id:cloudUser.id,payload:data,updated_at:new Date().toISOString()});if(result.error){setSyncStatus('동기화 오류','error');console.error(result.error)}else setSyncStatus(activeWorkspace?'가족 Workspace 저장됨':'클라우드 저장됨','online')}
async function refreshWorkspace(){activeWorkspace=null;if(!cloudClient||!cloudUser)return;const result=await cloudClient.rpc('get_my_workspace');if(!result.error&&result.data&&result.data.length)activeWorkspace=result.data[0];renderWorkspace();renderSyllabus()}
async function loadCloudData(){if(!cloudClient||!cloudUser)return;cloudLoading=true;setSyncStatus('클라우드 확인 중…','syncing');const result=activeWorkspace?await cloudClient.from('workspace_data').select('payload').eq('workspace_id',activeWorkspace.workspace_id).maybeSingle():await cloudClient.from('user_data').select('payload').eq('user_id',cloudUser.id).maybeSingle();if(result.error){setSyncStatus(activeWorkspace?'Workspace 설정 필요':'DB 설정 필요','error');cloudLoading=false;return}if(result.data&&result.data.payload&&Object.keys(result.data.payload).length){data=migrate(result.data.payload);window.__ibData=data;localStorage.setItem(KEY,JSON.stringify(data));renderAll();setSyncStatus(activeWorkspace?'가족 Workspace 연결됨':'클라우드 연결됨','online')}else{cloudLoading=false;await syncToCloud();setSyncStatus('첫 데이터 업로드됨','online');return}cloudLoading=false}
async function handleSession(session){cloudUser=session&&session.user?session.user:null;const button=document.querySelector('#accountButton');if(cloudUser){button.textContent=cloudUser.email||'계정';await refreshWorkspace();await loadCloudData()}else{activeWorkspace=null;button.textContent='로그인';setSyncStatus('이 기기에 저장됨','');renderWorkspace();renderSyllabus()}}
async function initCloud(){const cfg=window.IB_SUPABASE_CONFIG;if(!cfg||!window.supabase){setSyncStatus('오프라인 모드','error');return}cloudClient=window.supabase.createClient(cfg.url,cfg.publishableKey);const sessionResult=await cloudClient.auth.getSession();await handleSession(sessionResult.data.session);cloudClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(()=>handleSession(session),0)})}
function statusLabel(v){return {done:'✓ 완료',progress:'↻ 진행 중',todo:'○ 미완'}[v]}
function metrics(key){const list=allObjectives(key), states=list.map(o=>data.progress[o.id]||{}),done=states.filter(x=>x.status==='done').length,progress=states.filter(x=>x.status==='progress').length,gaps=list.filter(o=>isGap(o.id)).length;return{total:list.length,done,progress,gaps,pct:Math.round(done/list.length*100)}}
function isGap(id){const p=data.progress[id]||{};return p.school&&(p.status!=='done'||(+p.confidence||0)<3)}
function gapItems(){return Object.keys(SUBJECTS).flatMap(k=>allObjectives(k).filter(o=>isGap(o.id)).map(o=>({...o,subject:k})));}
function renderAll(){renderDashboard();renderSyllabus();renderLearningObjectives();renderPractice();renderFlashcards();renderFocus();}
const VIETA_SKILLS=[['Extract root–coefficient relationships','Unstable','Drill 5/5 · Day 25 0/2'],['Calculate sums of squares','Learning','Drill 2/4 · Day 25 0/2'],['Calculate sums of reciprocal roots','Independent','Drill Q1(c) · 2/2'],['Calculate sums of cubes','Learning','Drill Q1(d), Q4(c) · 1/5'],['Calculate higher-power symmetric sums','Learning','Drill Q4(d) · 1/2'],['Construct polynomials with transformed roots','Not learned','Scaled 0/3 · Reciprocal 0/3'],['Determine unknown roots from conditions','With help','Drill 3/4 · Day 25 partial method'],['Prove identities using Vieta’s formulas','Not learned','Drill Q5 · 1/6']];
const ANNUITY_SKILLS=[['Set up periodic compound-interest expressions','Learning','Annuity Drill P1(a) 0/1; P2–P6 setup strong after P6 correction'],['Compute the correct annual growth factor R','Learning','P2 used R=1.05 instead of (1+0.05/12)^12; answers mostly close'],['Apply GP sum formula for repeated deposits','Independent','All six problems used the annuity/GP structure correctly'],['Find threshold number of years','Learning','P5(c) chose n=6, but target required n=8'],['Check final values against the target condition','With help','Needs explicit “is it above the target?” check before final n']];
const PHYSICS_SKILL_CATALOG={
  'A1':['Describe and analyse motion in terms of position, velocity and acceleration','Recall that velocity is rate of change of position and acceleration is rate of change of velocity','Understand that change in position is displacement','Recall the difference between distance and displacement','Recall instantaneous and average values of velocity, speed and acceleration','Use SUVAT equations for uniformly accelerated motion','Understand motion with uniform and non-uniform acceleration','Understand projectile motion in the absence of fluid resistance','Recall the qualitative effect of fluid resistance on projectiles and terminal speed'],
  'A2':['Draw and interpret free-body diagrams','Apply Newton’s laws to one- and two-body systems','Resolve forces and calculate resultant force','Use impulse and momentum relationships','Apply conservation of momentum in collisions and explosions','Distinguish elastic and inelastic collisions'],
  'A3':['Calculate work done by a constant force','Use kinetic, gravitational and elastic potential energy models','Apply conservation of energy and energy-transfer diagrams','Calculate power and efficiency','Connect force-displacement graphs to work and energy'],
  'A4':['Describe rotational motion using angular displacement, velocity and acceleration','Calculate torque and use rotational equilibrium','Use moment of inertia and rotational kinetic energy','Apply angular momentum conservation','Compare translational and rotational models'],
  'A5':['Explain reference frames and Galilean transformations','Apply postulates of special relativity qualitatively','Use time dilation and length contraction relationships','Interpret spacetime events and causality','Recognize limits of classical mechanics at high speed'],
  'B1':['Describe thermal energy transfer by conduction, convection and radiation','Use specific heat capacity and specific latent heat','Interpret heating and cooling curves','Apply thermal equilibrium concepts','Solve energy-transfer problems with units'],
  'B2':['Explain the greenhouse effect and energy balance','Distinguish absorption, reflection and emission of radiation','Use simple climate-energy models','Interpret albedo and emissivity qualitatively','Evaluate physical assumptions in climate contexts'],
  'B3':['Use ideal gas equation and gas-law relationships','Connect macroscopic gas behaviour to particle motion','Interpret pressure, volume and temperature changes','Use Kelvin temperature correctly','Solve multi-step gas-law problems'],
  'B4':['Apply the first law of thermodynamics','Describe entropy and the second law qualitatively','Analyse thermodynamic processes and cycles','Distinguish heat, work and internal energy','Evaluate efficiency limits of heat engines'],
  'B5':['Define current, potential difference and resistance','Use Ohm’s law and power relationships','Analyse series and parallel circuits','Interpret circuit diagrams and meter readings','Use internal resistance and emf where appropriate'],
  'C1':['Describe simple harmonic motion conditions','Use displacement, velocity, acceleration and energy in SHM','Interpret SHM graphs','Apply period and frequency relationships','Connect SHM to pendulum and spring systems'],
  'C2':['Describe waves using amplitude, wavelength, frequency and speed','Use the wave equation','Distinguish transverse and longitudinal waves','Apply superposition qualitatively and quantitatively','Interpret wavefronts and ray diagrams'],
  'C3':['Explain reflection, refraction, diffraction and interference','Use Snell’s law where appropriate','Analyse standing-wave and interference patterns','Apply single-slit and double-slit ideas qualitatively','Connect wave phenomena to real systems'],
  'C4':['Describe formation of standing waves','Identify nodes, antinodes and harmonics','Use resonance and natural frequency concepts','Solve string and pipe resonance problems','Interpret resonance risks and applications'],
  'C5':['Explain Doppler effect for sound and light qualitatively','Use Doppler relationships in suitable contexts','Distinguish source and observer motion effects','Interpret redshift and blueshift examples','Apply Doppler ideas to measurement contexts'],
  'D1':['Describe gravitational field strength and potential','Apply Newton’s law of gravitation','Analyse circular or orbital motion in gravitational fields','Use field diagrams and equipotentials','Connect energy changes to gravitational potential'],
  'D2':['Describe electric and magnetic fields','Use Coulomb’s law and electric field strength','Analyse charged particles and currents in magnetic fields','Use field-line and equipotential representations','Compare gravitational, electric and magnetic field models'],
  'D3':['Analyse motion of charged particles in electric fields','Analyse motion of charged particles in magnetic fields','Connect force direction to field and velocity directions','Solve circular-motion cases in magnetic fields','Interpret electromagnetic-field applications'],
  'D4':['Explain magnetic flux and flux linkage','Apply Faraday’s law and Lenz’s law','Analyse induced emf in coils and conductors','Describe generators and transformers','Use energy conservation in induction contexts'],
  'E1':['Describe atomic structure and nuclear notation','Explain emission and absorption spectra','Use energy-level diagrams','Connect photons to energy transitions','Interpret evidence for atomic models'],
  'E2':['Describe wave-particle duality','Use photon energy and de Broglie wavelength relationships','Explain photoelectric-effect observations','Interpret quantum uncertainty qualitatively','Connect quantum models to experimental evidence'],
  'E3':['Describe radioactive decay and nuclear stability','Use half-life relationships and decay graphs','Interpret activity and count-rate data','Identify alpha, beta and gamma radiation properties','Apply safety and shielding ideas'],
  'E4':['Explain nuclear fission and chain reactions','Use mass defect and binding energy ideas','Describe nuclear reactor energy transfers','Evaluate risks and benefits of fission power','Solve energy-release problems'],
  'E5':['Explain nuclear fusion conditions','Describe stellar energy production','Use mass-energy equivalence qualitatively and quantitatively','Interpret stellar lifecycle ideas at syllabus level','Connect fusion to energy and astrophysics contexts'],
  'XP1':['Record measurements with correct units and significant figures','Calculate absolute, fractional and percentage uncertainty','Propagate uncertainties in simple calculations','Draw and interpret graphs with error bars','Evaluate data quality and anomalous results'],
  'XP2':['Identify independent, dependent and controlled variables','Design a valid and repeatable experiment','Select appropriate apparatus and measurement range','Assess safety, precision and limitations','Suggest realistic improvements to a procedure'],
  'XP3':['Formulate a focused research question','Collect and process sufficient relevant data','Present analysis clearly with uncertainties','Evaluate conclusion against evidence','Communicate scientific investigation in IB style']
};
const PHYSICS_PRACTICE_DETAILS={
  'A1':{score:'12/14',scoreNote:'Projectile Q4–Q5 · 86%',description:'Projectile motion is mostly secure. The main remaining issue is selecting the resultant speed from horizontal and vertical velocity components.',skills:[['Initial vertical velocity in horizontal launch','Independent','Q4(a) 1/1 · correctly identified 0 m s⁻¹'],['Time of flight using vertical SUVAT','Independent','Q4(b) 2/2 and Q5(b) 3/3'],['Horizontal range using constant horizontal velocity','Independent','Q4(c) 2/2'],['Resolve angled launch into components','Independent','Q5(a) 2/2'],['Resultant velocity from components','Learning','Q4(d) 1/3 · calculated 33.3 m s⁻¹ but selected vertical speed 29.7 m s⁻¹'],['Explain acceleration at maximum height','Independent','Q5(c) 1/1 · wording can be polished']]},
  'A2':{score:'1/12',scoreNote:'Impulse/collision Q6–Q7 · 8%',description:'This is the largest current Physics weakness. Ivan needs to rebuild impulse as area under an F–t graph, impulse-momentum theorem, and vector momentum conservation.',skills:[['Impulse from force-time graph area','Not learned','Q6(a) 0/2 · used FΔt with zero instead of triangular area'],['Impulse-momentum theorem J = m(vf − vi)','Not learned','Q6(b) 0/3 · used J = mv and carried wrong impulse'],['Assumption behind F–t graph model','Not learned','Q6(c) 0/1 · assumption is about resultant impact force, not air resistance'],['Resolve momentum into x and y components','With help','Q7(a) 1/2 · method partly present but used wrong angle'],['Use correct collision geometry and signs','Not learned','Q7(b) treated as angle/sign error in final subtotal'],['Find resultant speed and direction from components','Not learned','Q7(c) 0/2 · added components arithmetically instead of vector magnitude/direction']]},
  'XP1':{score:'1/1',scoreNote:'Uncertainty MCQ · correct',description:'The latest uncertainty MCQ was correct, but this is a small evidence point. Keep XP1 in light review until longer uncertainty questions are available.',skills:[['Identify correct uncertainty concept in MCQ','Independent','Q8 1/1'],['Show uncertainty working in calculation questions','With help','Needs more evidence from written-response problems'],['Propagate uncertainties','With help','Keep as review target'],['Interpret graph/data uncertainty','With help','No recent evidence in this set']]}
};
const MATH_PRACTICE_DETAILS={
  'AHL 1.15':{score:'14/21',scoreNote:'Day 27–29 proof · 67%',description:'Induction is secure, but contradiction proof has a repeated pattern: Ivan sets up divisibility correctly, then loses marks on the final contradiction sentence or on using the previous irrational result.',skills:[['Verify induction base case and step','Independent','Day 27 Q1 · 7/8'],['Set up contradiction with coprime integers','Independent','Day 28–29 part (a) setup works'],['Complete contradiction conclusion','Learning','Day 28 and Day 29 both lost the final “therefore irrational” conclusion mark'],['Use previous result for related irrational expressions','Not learned','Day 28 Q1(b), Day 29 Q1(b) both 0/2'],['Avoid false general claims about irrational sums','Not learned','Day 29: “irrational + number is irrational” is not always true']]},
  'SL 1.2':{score:'7/8',scoreNote:'Day 28 Q2 · 88%',description:'Arithmetic sequences are mostly secure. The only missing step was converting the inequality boundary into the largest integer n.',skills:[['Find a term of an arithmetic sequence','Independent','Q2(a) 1/1'],['Solve for n from uₙ','Independent','Q2(b) 2/2'],['Derive a formula for Sₙ','Independent','Q2(c) 2/2'],['Solve Sₙ > 0 and select integer n','Learning','Q2(d) found n < 6.33 but did not state largest integer n = 6']]},
  'SL 2.5':{score:'5/7',scoreNote:'Day 28–29 inverse · 71%',description:'Inverse-function algebra was strong on Day 28, but Day 29 exposed the need to recognize and prove a self-inverse function directly.',skills:[['Rearrange rational function to find inverse','Independent','Day 28 Q3(b) 4/4'],['Recognize self-inverse structure','Learning','Day 29 Q2(c) partly correct: f⁻¹(x)=f(x)'],['Prove f(f(x)) = x by substitution','Not learned','Day 29 Q2(b) 1/3 · algebra setup started but not completed'],['State domain restrictions clearly','Learning','Keep writing x ≠ 2 when needed']]},
  'SL 2.8':{score:'13/19',scoreNote:'Day 28–29 rational functions · 68%',description:'Asymptotes are reliable, but intersections and graph details need more care. Day 29 rational-function algebra was a noticeable dip.',skills:[['Identify vertical and horizontal asymptotes','Independent','Day 28 and Day 29 asymptotes full marks'],['Sketch rational graph with key features','Learning','Day 28 sketch lost intercept label mark'],['Solve intersections with y=x','Not learned','Day 29 Q2(d) 1/3 · factorization error; roots are 2 ± √7'],['Prove self-inverse function behavior','Not learned','Day 29 Q2(b) 1/3 · complete f(f(x)) substitution'],['Avoid incorrect factorization','With help','Check expansion before accepting factors']]},
  'AHL 1.10':{score:'10/17',scoreNote:'Day 27–28 binomial · 59%',description:'Basic binomial terms are fine, but product coefficients remain a repeated focus item. Ivan needs to list all term-pair combinations that make the required power.',skills:[['Use the general term formula T_{r+1}','Learning','Flashcard added for Large T formula'],['Find individual binomial coefficients','Independent','Day 27 Q2(a)(b) correct; Day 28 Q7(a) correct'],['Calculate nCr accurately','With help','Day 28 Q7(b) used C(6,2)=6 instead of 15'],['Compute product coefficient by convolution','Not learned','Day 27 Q2(c) and Day 28 Q7(c) repeated error'],['Identify which powers combine to target power','Not learned','Use pairs such as (x⁰)(x³)+(x¹)(x²), not unrelated r values']]},
  'AHL 5.16':{score:'17/20',scoreNote:'Day 27–28 integration · 85%',description:'Integration by substitution and parts is now a strength. Remaining errors are final definite-integral arithmetic and choosing the correct prior result in “hence” questions.',skills:[['Use substitution in exponential/trig integrals','Independent','Day 27 Q3(a) and Day 28 Q6(a) correct'],['Apply integration by parts twice','Independent','Day 27 Q3(b) and Day 28 Q6(b) full marks'],['Choose correct earlier result for hence question','Learning','Day 27 Q3(c) used the wrong prior result'],['Evaluate definite integrals carefully','Learning','Day 28 Q6(c) final constant should be π²/4 − 2 = (π²−8)/4']]},
  'AHL 5.14':{score:'10/16',scoreNote:'Day 27–28 calculus · 63%',description:'Implicit differentiation mechanics improved, but related-rates chain rule and solving horizontal tangent points remain focus items.',skills:[['Differentiate implicitly','Independent','Day 28 Q5(a) 3/3'],['Find tangent equation at a point','Independent','Day 28 Q5(c) 2/2'],['Find horizontal tangent points','With help','Day 28 Q5(b) reached x+y=0 but final coordinates wrong'],['Apply related-rates chain rule','Not learned','Day 27 Q4(c) needs dV/dt = (dV/dh)(dh/dt)'],['Write contextual explanation in rates problems','Not learned','Day 27 Q4(d) omitted']]},
  'AHL 3.10':{score:'14/16',scoreNote:'Day 27–28 trig · 88%',description:'Compound-angle identities and solving are strong. The repeated weakness is no-solution parameter ranges: distinguish when solutions exist from when they do not.',skills:[['Expand compound-angle identities','Independent','Day 27 Q5(a), Day 28 Q4(a) full marks'],['Solve trigonometric equations','Independent','Day 27 Q5(b), Day 28 Q4(b) full marks'],['Find expression range before applying k','Learning','For √2 cos x or √3 cos x, write the full LHS range first'],['State no-solution parameter values','With help','Repeated error: wrote existence range instead of no-solution range'],['Separate variable x from parameter k','Learning','Recurring Day 26–28 pattern']]},
  'AHL 2.14':{score:'5/6',scoreNote:'Day 29 Q3 odd/even · strong',description:'Odd/even recognition and sketch interpretation were good. The weakness is not the symmetry itself, but carrying inequality intervals correctly after finding roots.',skills:[['Show an odd function using g(-x)=-g(x)','Independent','Q3(a) full marks for g'],['Show an even function using h(-x)=h(x)','Independent','Q3(a) full marks for h'],['Use symmetry in sketching','Independent','Q3(d) 2/2'],['Carry interval signs into final solution','Learning','Q3(b)(c) interval direction error']]},
  'AHL 2.15':{score:'3/5',scoreNote:'Day 29 Q3 inequality · 60%',description:'The algebraic setup and roots were mostly correct, but final interval selection needs sign-chart discipline.',skills:[['Form inequality from two functions','Independent','Q3(b) formed x³−x²−3x−1 > 0'],['Factor polynomial inequality','Independent','Q3(b) factorization accepted'],['Find critical roots','Independent','Roots −1, 1±√2 found'],['Select correct sign intervals','Not learned','Q3(b) final interval direction wrong'],['Use complement for “hence ≤” questions','Not learned','Q3(c) inherited wrong interval; correct is x≤−1 or 1−√2≤x≤1+√2']]},
  'AHL 3.9':{score:'12/14',scoreNote:'Day 29 Q4 inverse trig · 86%',description:'Inverse trig domain/range and equation solving are strong. The remaining issue is finishing algebra and rejecting invalid roots in arctan addition problems.',skills:[['Recall domain/range of arcsin, arccos, arctan','Independent','Q4(a) 3/3'],['Solve arcsin equation','Independent','Q4(b) 2/2'],['Solve arccos equation','Independent','Q4(c) 3/3'],['Use arctan addition formula','Learning','Q4(d) reached 3x²+4x−1=0 but did not finish'],['Check validity of arctan roots','With help','Reject root that does not satisfy the original angle condition'],['Sketch arctan with asymptotes','Independent','Q4(e) 2/2']]},
  'AHL 2.16':{score:'7/9',scoreNote:'Day 29 Q5 absolute value · 78%',description:'Solving absolute value equations/inequalities is mostly good. Sketch labels and “hence” complements need tightening.',skills:[['Solve absolute-value equation by cases','Independent','Q5(a) 3/3'],['Solve strict absolute-value inequality','Independent','Q5(b) 2/2'],['Sketch absolute-value graph and line','Learning','Q5(c) 2/3 · intersection coordinate labels unclear'],['Use complement for ≤ from >','Not learned','Q5(d) 0/1 · should be 2/3 ≤ x ≤ 4'],['Check candidate intervals against graph','Learning','Use graph to verify inequality direction']]},
};
const MATH_SKILL_CATALOG={
  'SL 1.1':['Convert numbers between ordinary and scientific notation','Perform calculations and round to a stated accuracy','Use significant figures and percentage error in context'],
  'SL 1.2':['Recognize and generate arithmetic sequences','Use the nth-term formula','Find finite arithmetic series and solve contextual problems'],
  'SL 1.3':['Recognize and generate geometric sequences','Use geometric nth-term and finite-sum formulae','Model growth and decay with geometric sequences'],
  'SL 1.4':['Apply compound-interest and depreciation models','Distinguish nominal and effective rates','Solve loan, annuity and investment problems with technology'],
  'SL 1.5':['Apply laws of indices','Apply laws of logarithms','Change logarithm base and simplify exponential expressions'],
  'SL 1.6':['Use implication, equivalence and mathematical notation','Construct a direct deductive proof','Identify gaps or invalid steps in an argument'],
  'SL 1.7':['Solve exponential equations using logarithms','Solve logarithmic equations and check domain restrictions','Interpret solutions in growth and decay contexts'],
  'SL 1.8':['Determine whether a geometric series converges','Find the sum to infinity','Use infinite series in recurring-decimal and contextual problems'],
  'SL 1.9':['Expand positive-integer binomials','Find a specified term or coefficient','Use Pascal’s triangle and combinations efficiently'],
  'AHL 1.10':['Apply permutations and combinations','Expand binomials with fractional or negative powers','State and use the interval of validity of an expansion'],
  'AHL 1.11':['Recognize a proper rational expression','Decompose a denominator with up to two distinct linear factors','Use partial fractions to simplify later calculus work'],
  'AHL 1.12':['Operate with complex numbers in Cartesian form','Find conjugate, modulus and argument','Represent complex numbers on an Argand diagram'],
  'AHL 1.13':['Convert between Cartesian, polar and Euler forms','Multiply and divide complex numbers geometrically','Interpret modulus and argument transformations'],
  'AHL 1.14':['Use conjugate-pair roots for real polynomials','Apply and prove De Moivre’s theorem','Find and display powers and roots of complex numbers'],
  'AHL 1.15':['Construct a proof by mathematical induction','Construct a proof by contradiction','Disprove a statement with a justified counterexample'],
  'AHL 1.16':['Represent a system of up to three linear equations','Solve systems using algebra or technology','Interpret unique, infinite and nonexistent solutions geometrically'],
  'SL 2.1':['Use gradient, intercept and point-gradient forms of a line','Determine parallel and perpendicular lines','Solve intersection and distance problems with straight lines'],
  'SL 2.2':['Identify domain and range from rules or graphs','Use function notation and evaluate functions','Choose domain restrictions that make an inverse possible'],
  'SL 2.3':['Sketch a graph from its equation or key information','Use technology to produce an accurate graph','Select a useful viewing window and interpret graphical evidence'],
  'SL 2.4':['Find intercepts, extrema and axes of symmetry','Identify asymptotes and end behaviour','Read intervals of increase, decrease and sign from a graph'],
  'SL 2.5':['Form and evaluate composite functions','Find an inverse function algebraically','Verify inverse and composite relationships with domains'],
  'SL 2.6':['Move between standard, factorized and vertex forms','Find roots, vertex and axis of symmetry','Model and solve a contextual problem with a quadratic'],
  'SL 2.7':['Solve quadratic equations exactly and numerically','Use the discriminant to classify roots','Solve quadratic inequalities using algebra and graphs'],
  'SL 2.8':['Identify vertical and horizontal asymptotes','Sketch reciprocal and simple rational functions','Connect algebraic restrictions, intercepts and graph behaviour'],
  'SL 2.9':['Sketch exponential and logarithmic functions','Use inverse relationships between exponentials and logarithms','Interpret parameters in growth and decay models'],
  'SL 2.10':['Find intersections and roots graphically','Solve equations analytically where possible','Use technology and report all solutions in a stated domain'],
  'SL 2.11':['Apply translations, reflections and stretches to graphs','Describe a transformation from equations or graphs','Combine transformations in the correct order'],
  'AHL 2.12':['Use zeros, roots and factors of polynomial functions','Apply the factor and remainder theorems','Relate polynomial roots to coefficients using Vieta’s formulas'],
  'AHL 2.13':['Find vertical, horizontal and oblique asymptotes','Sketch higher rational functions with intercepts','Use algebra and technology to verify rational graph behaviour'],
  'AHL 2.14':['Test whether a function is odd, even or neither','Restrict a domain and find an inverse','Recognize and verify self-inverse and periodic functions'],
  'AHL 2.15':['Solve inequalities of the form g(x) ≥ f(x) graphically','Solve polynomial inequalities up to degree three analytically','Use sign diagrams and technology to verify solution intervals'],
  'AHL 2.16':['Sketch modulus, reciprocal and squared function transformations','Solve modulus equations and inequalities','Analyse transformations of f(ax+b), |f(x)| and f(|x|)'],
  'SL 3.1':['Identify right triangles in 3D objects','Calculate distance, midpoint, angles, surface area and volume','Solve multi-step 3D geometry problems with correct units'],
  'SL 3.2':['Apply the sine rule and cosine rule','Calculate triangle area using trigonometric formulae','Choose the correct rule from given side and angle information'],
  'SL 3.3':['Model bearings and navigation diagrams','Solve contextual trigonometry problems','Communicate angles, distances and assumptions clearly'],
  'SL 3.4':['Convert between degrees and radians','Calculate arc length and sector area','Use radian measure naturally in circular-motion contexts'],
  'SL 3.5':['Use unit-circle definitions of sine, cosine and tangent','Find exact values and quadrant-related values','Handle ambiguous sine-rule cases'],
  'SL 3.6':['Apply Pythagorean identities and tangent relationships','Use double-angle identities for sine and cosine','Derive unknown ratios without finding the angle'],
  'SL 3.7':['Sketch sine, cosine and tangent graphs','Identify amplitude, period, phase shift and vertical shift','Model periodic real-world situations with transformed trigonometric functions'],
  'SL 3.8':['Solve trigonometric equations in a finite interval','Use graphs and algebra to find all solutions','Reduce equations to quadratic form in sine, cosine or tangent'],
  'AHL 3.9':['Use reciprocal trigonometric ratios and identities','Sketch and interpret inverse trigonometric functions with domains and ranges','Solve problems involving sec, cosec, cot and inverse trigonometric functions'],
  'AHL 3.10':['Apply compound-angle identities','Use the double-angle identity for tangent','Derive and select identities efficiently in proofs and equations'],
  'AHL 3.11':['Use symmetry properties of trigonometric functions','Transform angles using related-angle identities','Connect algebraic identities to graph symmetry'],
  'AHL 3.12':['Represent vectors in component and base-vector form','Perform vector addition, subtraction, scalar multiplication and magnitude calculations','Use vectors to prove geometric properties'],
  'AHL 3.13':['Calculate scalar products and angles','Test for perpendicular and parallel vectors','Use the scalar product in geometric and vector proofs'],
  'AHL 3.14':['Form vector equations of lines in two and three dimensions','Convert between point-direction and parametric forms','Solve position problems using line equations'],
  'AHL 3.15':['Classify two lines as coincident, parallel, intersecting or skew','Find intersection points when they exist','Interpret systems of vector equations geometrically'],
  'AHL 3.16':['Compute vector products and normal vectors','Use the cross product to find areas and perpendicular directions','Apply the vector product to 3D geometry problems'],
  'AHL 3.17':['Form vector and Cartesian equations of planes','Use normal vectors and spanning vectors','Convert between plane representations'],
  'AHL 3.18':['Find line-plane and plane-plane intersections','Calculate angles between lines, planes and line-plane pairs','Interpret solution sets of 3D systems geometrically'],
  'SL 4.1':['Distinguish population, sample and sampling methods','Identify bias, reliability and validity issues','Handle outliers appropriately in statistical contexts'],
  'SL 4.2':['Construct and interpret frequency tables and grouped data displays','Draw and read histograms and cumulative frequency graphs','Use box plots to compare distributions'],
  'SL 4.3':['Calculate mean, median, mode, quartiles and percentiles','Calculate range, interquartile range and standard deviation','Choose appropriate summary statistics for a data set'],
  'SL 4.4':['Calculate and interpret correlation coefficient','Find and use the least-squares regression line of y on x','Judge when interpolation or extrapolation is reasonable'],
  'SL 4.5':['Identify trials, outcomes, sample spaces and events','Calculate expected number of occurrences','Use set notation and Venn diagrams for probability events'],
  'SL 4.6':['Calculate combined probabilities with addition and multiplication rules','Use tree diagrams, tables and Venn diagrams','Distinguish mutually exclusive and independent events'],
  'SL 4.7':['Define a discrete random variable and its probability distribution','Calculate expected value and variance','Interpret expected value in games and contextual problems'],
  'SL 4.8':['Recognize conditions for a binomial distribution','Calculate exact and cumulative binomial probabilities','Find mean and variance of a binomial random variable'],
  'SL 4.9':['Use normal-distribution notation and parameters','Calculate probabilities and inverse probabilities with technology','Interpret normal models in context'],
  'SL 4.10':['Find and interpret the least-squares regression line of x on y','Compare y-on-x and x-on-y regression lines','Use regression appropriately for prediction'],
  'SL 4.11':['Calculate conditional probability','Test independence using conditional probability','Solve multi-step probability problems with tables, trees or Venn diagrams'],
  'SL 4.12':['Standardize normal variables using z-scores','Use standardized normal probabilities and inverse values','Translate between raw scores, z-scores and percentiles'],
  'AHL 4.13':['Apply Bayes’ theorem','Use probability trees and formulae for reverse conditional probability','Interpret posterior probability in context'],
  'AHL 4.14':['Work with discrete and continuous random variables','Use probability density functions and cumulative distribution functions','Calculate expectation and variance in advanced distributions'],
  'SL 5.1':['Understand limits as gradients and rates of change','Estimate derivatives from tables, graphs and technology','Interpret instantaneous rate of change in context'],
  'SL 5.2':['Identify intervals where a function is increasing or decreasing','Use derivative signs to justify monotonic behaviour','Connect derivative graphs to original-function behaviour'],
  'SL 5.3':['Differentiate polynomial functions','Apply the power rule and constant multiple rule','Use derivatives to solve routine algebraic problems'],
  'SL 5.4':['Find equations of tangents and normals','Interpret derivative values as gradients and rates','Use derivative notation accurately in solutions'],
  'SL 5.5':['Use technology to evaluate definite integrals','Interpret definite integrals as signed area','Estimate area under a curve in context'],
  'SL 5.6':['Apply the chain rule','Apply the product rule','Apply the quotient rule in multi-step differentiation'],
  'SL 5.7':['Use second derivatives to determine concavity','Identify local maxima, minima and points of inflexion','Connect first and second derivatives to graph shape'],
  'SL 5.8':['Set up optimization problems from context','Use derivatives to find and classify extrema','Interpret optimal values with units and domain restrictions'],
  'SL 5.9':['Use calculus with displacement, velocity and acceleration','Differentiate and integrate kinematic functions','Interpret motion graphs and constants of integration'],
  'SL 5.10':['Find indefinite integrals using reverse differentiation','Use substitution in accessible integration problems','Include and interpret constants of integration'],
  'SL 5.11':['Evaluate definite integrals analytically','Find areas between curves','Handle intersections and sign changes when calculating area'],
  'AHL 5.12':['Analyze continuity and differentiability','Evaluate limits algebraically and graphically','Derive derivatives from first principles'],
  'AHL 5.13':['Evaluate advanced limits','Apply l’Hôpital’s rule where appropriate','Recognize indeterminate forms and choose a valid method'],
  'AHL 5.14':['Differentiate implicitly','Set up and solve related-rates problems','Interpret linked changing quantities in context'],
  'AHL 5.15':['Differentiate exponential, logarithmic and trigonometric functions','Find antiderivatives of advanced standard functions','Select efficient differentiation and integration strategies'],
  'AHL 5.16':['Use integration by substitution','Use integration by parts','Choose between substitution and parts in unfamiliar integrals'],
  'AHL 5.17':['Calculate areas with respect to the y-axis','Set up volumes of revolution','Evaluate and interpret volume integrals'],
  'AHL 5.18':['Form and solve first-order differential equations','Use separation of variables','Apply Euler’s method and interpret approximation error'],
  'AHL 5.19':['Construct Maclaurin series for standard functions','Use series to approximate function values','Determine validity and error considerations for series approximations']
};
function masteryLabel(p){if(p.status==='done'&&+p.confidence>=4)return'Independent';if(p.status==='done')return'Learning';if(p.status==='progress')return'With help';return'Not learned'}
function genericMathSkills(o){const topic=o.group.replace(/^Topic\s+\d+\s*[·—-]\s*/,'');return[
  [`Recognize the notation and key ideas used in ${o.title}`,`Define the terms and identify when the method applies · ${topic}`],
  [`Carry out the standard procedure for ${o.title}`,'Complete a routine question accurately without notes'],
  [`Apply ${o.title} in a multi-step problem`,'Select the method independently and connect it to earlier topics'],
  [`Explain and verify a solution involving ${o.title}`,'Use correct notation, justify steps and check whether the answer is reasonable']
]}
function mathLearningDetails(o){const practice=MATH_PRACTICE_DETAILS[o.code];if(practice)return{title:o.title,description:practice.description,skills:practice.skills,score:practice.score,scoreNote:practice.scoreNote};if(o.code==='SL 1.4')return{title:'Financial applications · annuities',description:'Use compound-interest and geometric-series models for repeated deposits, then verify the required number of years.',skills:ANNUITY_SKILLS,score:'32/36',scoreNote:'Annuity Drill · 89%'};if(o.code==='AHL 2.12')return{title:'Vieta’s formulas',description:'Relate polynomial roots to coefficients and use those relationships in calculations, constructions and proofs.',skills:VIETA_SKILLS,score:'21/44',scoreNote:'2 sets · 48%'};const p=data.progress[o.id]||{status:'todo',confidence:0},label=masteryLabel(p),catalog=MATH_SKILL_CATALOG[o.code],raw=catalog?catalog.map((title,i)=>[title,`Demonstrate this skill independently in an IB-style question · Check ${i+1} of ${catalog.length}`]):genericMathSkills(o);return{title:o.title,description:catalog?'Specific mastery checks derived from the current IB Mathematics: Analysis and Approaches guide.':'Guide-aligned mastery checks for this Mathematics: Analysis and Approaches syllabus statement.',skills:raw.map((s,i)=>[s[0],i<Math.max(0,+p.confidence-1)?label:'Not learned',s[1]]),score:(+p.confidence||0)+'/5',scoreNote:statusLabel(p.status||'todo')}}
function physicsLearningDetails(o){const practice=PHYSICS_PRACTICE_DETAILS[o.code];if(practice)return{title:o.title,description:practice.description,skills:practice.skills,score:practice.score,scoreNote:practice.scoreNote};const p=data.progress[o.id]||{status:'todo',confidence:0},label=masteryLabel(p),catalog=PHYSICS_SKILL_CATALOG[o.code]||[];const raw=catalog.map((title,i)=>[title,`Draft Physics learning objective · ${o.code}.${i+1}`]);return{title:o.title,description:'Draft learning-objective checklist for this IB Physics subtopic. Use it to review Ivan’s practice results and refine the wording against school materials.',skills:raw.map((s,i)=>[s[0],i<Math.max(0,+p.confidence-1)?label:'Not learned',s[1]]),score:(+p.confidence||0)+'/5',scoreNote:statusLabel(p.status||'todo')}}
function learningDetails(o){return o.subject==='physics'?physicsLearningDetails(o):mathLearningDetails(o)}
function renderLearningObjectives(){const el=document.querySelector('#learningObjectivePanel');if(el)el.innerHTML='';if(!['math','physics'].includes(selectedSubject))return;document.querySelectorAll('.objective').forEach(row=>{const codeEl=row.querySelector('code'),code=codeEl?codeEl.textContent.trim():'',o=allObjectives(selectedSubject).find(item=>item.code===code);if(!o||row.querySelector('.lo-summary'))return;row.classList.add('has-learning-detail');const p=data.progress[o.id]||{},loCount=o.subject==='physics'?(PHYSICS_SKILL_CATALOG[o.code]||[]).length:0,label=o.subject==='physics'?`${loCount} LO 보기`:o.code==='AHL 2.12'?'48% · 4 weak · LO 보기':`${p.confidence||0}/5 · LO 보기`;row.querySelector('.objective-title').insertAdjacentHTML('beforeend',`<button class="lo-summary" data-open-lo="${o.id}">${label} →</button>`)})}
function openLearningObjectiveDrawer(id){const o=findObjective(id);if(!o)return;const d=learningDetails(o),content=document.querySelector('#learningObjectiveDrawerContent'),source=o.subject==='math'?'<p class="lo-source">Source: <a href="https://www.ibo.org/globalassets/new-structure/university-admission/pdfs/dp-mathematics-analysis-and-approaches-guide-en.pdf" target="_blank" rel="noopener">IB Mathematics: Analysis and Approaches guide</a></p>':'<p class="lo-source">Source: Draft aligned to the current IB Physics syllabus structure; refine with school checklist if available.</p>';content.innerHTML=`<div class="lo-head"><div><span class="eyebrow">${escapeHtml(o.code)} · ${escapeHtml(o.category)}</span><h2>${escapeHtml(d.title)}</h2><p>${escapeHtml(d.description)}</p>${source}</div><strong>${escapeHtml(d.score)}<small>${escapeHtml(d.scoreNote)}</small></strong></div><div class="lo-grid">${d.skills.map((s,i)=>`<div class="lo-skill"><code>${o.code==='AHL 2.12'?'Skill '+(i+1):(o.subject==='physics'?o.code+'.'+(i+1):'Check '+(i+1))}</code><b>${escapeHtml(s[0])}</b><span class="mastery ${String(s[1]).toLowerCase().replace(/ /g,'-')}">${escapeHtml(s[1])}</span><small>${escapeHtml(s[2])}</small></div>`).join('')}</div>`;document.querySelector('#learningObjectiveDrawer').showModal()}
function renderDashboard(){
  const all=Object.keys(SUBJECTS).map(metrics), total=all.reduce((n,m)=>n+m.total,0),done=all.reduce((n,m)=>n+m.done,0),pct=Math.round(done/total*100);document.querySelector('#overallMastery').textContent=pct+'%';
  document.querySelector('#subjectCards').innerHTML=Object.entries(SUBJECTS).map(([k,s])=>{const m=metrics(k);return `<button class="subject-card" data-subject-open="${k}" style="--accent:${s.color};--tint:${s.tint};text-align:left;color:inherit"><div class="subject-card-top"><span class="subject-icon">${s.icon}</span><small>${m.gaps} focus items</small></div><h3>${s.name}</h3><small>${m.done} of ${m.total} objectives mastered</small><div class="metric"><strong>${m.pct}%</strong><small>${m.progress} in progress</small></div><div class="progress-track"><i style="width:${m.pct}%"></i></div></button>`}).join('');
  const gaps=gapItems();document.querySelector('#gapBadge').textContent=gaps.length;document.querySelector('#priorityList').innerHTML=gaps.slice(0,4).map(o=>`<div class="priority-item"><span class="priority-code">${o.code}</span><span><b>${o.title}</b><small>${SUBJECTS[o.subject].name} · ${o.category}</small></span><span class="tag">Review</span></div>`).join('')||'<div class="empty">현재 우선 복습 항목이 없습니다.</div>';
  const recent=data.practice.slice(-7);document.querySelector('#scoreChart').innerHTML='<i class="target-line"></i>'+recent.map((p,i)=>`<div class="chart-bar" style="--score:${Math.max(4,p.score)}%" data-score="${p.score}%"><span>${p.name.slice(0,5)}</span></div>`).join('');
  const completedThisWeek=Math.min(15,done);document.querySelector('#weeklyTarget').textContent=`${completedThisWeek} / 15`;document.querySelector('#weeklyBar').style.width=Math.round(completedThisWeek/15*100)+'%';
}
function renderTabs(){document.querySelector('#subjectTabs').innerHTML=Object.entries(SUBJECTS).map(([k,s])=>`<button data-subject="${k}" class="${k===selectedSubject?'active':''}">${s.short}</button>`).join('')}
function renderSyllabus(){renderTabs();const searchEl=document.querySelector('#searchInput'),filterEl=document.querySelector('#statusFilter'),q=searchEl?searchEl.value.toLowerCase():'',filter=filterEl?filterEl.value:'all',m=metrics(selectedSubject),canManage=!activeWorkspace||activeWorkspace.member_role==='owner';document.querySelector('#addObjective').classList.toggle('owner-only-hidden',!canManage);document.querySelector('#syllabusSummary').innerHTML=`<div class="summary-metric"><strong>${m.total}</strong><span>전체 항목</span></div><div class="summary-metric"><strong>${m.done}</strong><span>완료</span></div><div class="summary-metric"><strong>${m.progress}</strong><span>진행 중</span></div><div class="summary-metric"><strong>${m.gaps}</strong><span>Focus gaps</span></div><div class="summary-metric"><strong>${m.pct}%</strong><span>Mastery</span></div>`;
  const grouped={};allObjectives(selectedSubject).forEach(o=>{if(!grouped[o.group])grouped[o.group]=[];grouped[o.group].push(o)});document.querySelector('#syllabusList').innerHTML=Object.entries(grouped).map(([group,items])=>{const objs=items.filter(o=>{const p=data.progress[o.id]||{status:'todo'};return(!q||(o.code+' '+o.title+' '+o.category).toLowerCase().includes(q))&&(filter==='all'||filter==='gap'&&isGap(o.id)||p.status===filter)});if(!objs.length)return'';return `<section class="syllabus-group"><button class="group-header"><span>${group}</span><small>${objs.length} objectives</small><span class="chevron">⌄</span></button><div class="objective-list">${objs.map(o=>{const p=data.progress[o.id]||{school:false,status:'todo',confidence:0};return `<div class="objective"><code>${o.code}</code><div class="objective-title"><div><b>${o.title}</b><small>${o.category}</small></div>${canManage?`<button class="objective-edit" data-edit-objective="${o.id}" title="항목 편집">✎</button>`:''}</div><button class="school-toggle ${p.school?'taught':''}" data-school="${o.id}">${p.school?'✓ 학교 완료':'학교 미진도'}</button><select class="status-select" data-status="${o.id}"><option value="todo" ${p.status==='todo'?'selected':''}>○ 미완</option><option value="progress" ${p.status==='progress'?'selected':''}>↻ 진행 중</option><option value="done" ${p.status==='done'?'selected':''}>✓ 완료</option></select><select class="confidence-select" data-confidence="${o.id}" aria-label="자신감"><option value="0" ${!p.confidence?'selected':''}>자신감 —</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${+p.confidence===n?'selected':''}>${'★'.repeat(n)} ${n}</option>`).join('')}</select><span class="gap-dot ${isGap(o.id)?'active':''}" title="${isGap(o.id)?'복습 필요':'Gap 없음'}"></span></div>`}).join('')}</div></section>`}).join('')||'<div class="empty">조건에 맞는 syllabus 항목이 없습니다.</div>'}
function renderPractice(){const scores=data.practice.map(p=>+p.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,atTarget=scores.filter(x=>x>=75).length,last=scores.length?scores[scores.length-1]:0;document.querySelector('#practiceStats').innerHTML=[['기록',data.practice.length,'#587b96'],['평균 점수',avg+'%','#bd6549'],['목표 달성',atTarget+'회','#d6a44f'],['최근 점수',last+'%','#204b40']].map(x=>`<div class="stat-card" style="--accent:${x[2]}"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');document.querySelector('#practiceTable').innerHTML=[...data.practice].reverse().map(p=>`<tr><td>${p.date}</td><td>${SUBJECTS[p.subject].name}</td><td><b>${p.name}</b></td><td>${p.topic||'—'}</td><td class="score-cell">${p.score}%</td><td>${p.notes||'—'}</td></tr>`).join('')}
function today(){return new Date().toISOString().slice(0,10)}
function dueCards(){return data.flashcards.filter(c=>(c.due||today())<=today())}
function renderFlashcards(){
  const due=dueCards(),mastered=data.flashcards.filter(c=>(c.interval||0)>=14).length,reviewed=data.flashcards.reduce((n,c)=>n+(c.reviews||0),0);document.querySelector('#cardBadge').textContent=due.length;
  document.querySelector('#flashcardStats').innerHTML=[['전체 카드',data.flashcards.length,'#587b96'],['오늘 복습',due.length,'#bd6549'],['장기 기억',mastered,'#d6a44f'],['누적 복습',reviewed,'#204b40']].map(x=>`<div class="stat-card" style="--accent:${x[2]}"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');
  if(!currentCardId||!data.flashcards.some(c=>c.id===currentCardId))currentCardId=due.length?due[0].id:null;const card=data.flashcards.find(c=>c.id===currentCardId);
  document.querySelector('#reviewStage').innerHTML=!card?`<div class="review-empty"><span class="empty-icon">✓</span><h2>오늘 복습 완료!</h2><p>예정된 Flashcard를 모두 학습했습니다. 새 카드를 만들거나 내일 다시 확인하세요.</p><button class="primary" data-new-card>새 카드 만들기</button></div>`:`<div class="review-card"><div class="review-meta"><span>${SUBJECTS[card.subject].name}</span><span>${card.code||'No code'}</span><span>${card.type}</span></div><div class="flip-card" data-flip-card>${answerVisible?`<div class="answer">${formatFlashcardAnswer(card)}</div><p>기억 정도를 선택하세요</p>`:`<h2>${escapeHtml(card.front)}</h2><p>카드를 눌러 정답 보기</p>`}</div>${answerVisible?`<div class="rating-buttons"><button data-rate="again">다시<br><small>오늘</small></button><button data-rate="hard">어려움<br><small>1일</small></button><button data-rate="good">보통<br><small>${nextInterval(card,'good')}일</small></button><button data-rate="easy">쉬움<br><small>${nextInterval(card,'easy')}일</small></button></div>`:''}</div>`;
  const filter=document.querySelector('#cardSubjectFilter').value;const cards=data.flashcards.filter(c=>filter==='all'||c.subject===filter);document.querySelector('#cardLibrary').innerHTML=cards.map(c=>`<div class="library-card ${c.id===currentCardId?'active':''}" data-card-id="${c.id}" role="button" tabindex="0"><span><b>${escapeHtml(c.front)}</b><small>${SUBJECTS[c.subject].short} · ${c.code||c.type} · <span class="${(c.due||today())<=today()?'due-pill':''}">${(c.due||today())<=today()?'오늘 복습':'다음 '+c.due}</span></small></span><button data-delete-card="${c.id}" title="카드 삭제">×</button></div>`).join('')||'<div class="empty">카드가 없습니다.</div>'
}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function formatFlashcardAnswer(card){
  if(card&&card.id==='card-binomial-general-term')return `<div class="math-answer"><span class="math-label">General term</span><div class="math-formula"><span class="math-symbol">T<sub>r+1</sub></span><span>=</span><span class="binom"><span>n</span><span>r</span></span><span>a<sup>n-r</sup>b<sup>r</sup></span></div><div class="math-note">또는 <span class="math-symbol">T<sub>r+1</sub></span> = <span class="math-symbol">C(n,r)</span> · <span>a<sup>n-r</sup></span> · <span>b<sup>r</sup></span></div><div class="math-warning">주의: r번째 항이 아니라 <b>(r+1)번째 항</b>이다.</div></div>`;
  if(card&&card.id==='card-limit-xlnx-lhopital')return `<div class="math-answer"><span class="math-label">L’Hôpital setup</span><div class="math-formula"><span class="math-symbol">x ln x</span><span>=</span><span class="frac"><span>ln x</span><span>x<sup>-1</sup></span></span></div><div class="math-note">This becomes <b>−∞ / +∞</b>, so L’Hôpital applies.</div><div class="math-formula small"><span class="frac"><span>1/x</span><span>−1/x<sup>2</sup></span></span><span>=</span><span>−x</span><span>→</span><span>0</span></div><div class="math-warning">Ivan trap: <b>(1/x)/(−1/x²)</b> is not <b>1/0</b>. 복잡한 분수는 reciprocal로 곱해서 정리한다.</div></div>`;
  return escapeHtml(card&&card.back).replace(/\n/g,'<br>');
}
function nextInterval(card,rating){const current=card.interval||0;if(rating==='again')return 0;if(rating==='hard')return 1;if(rating==='easy')return current<1?4:Math.max(4,Math.round(current*2.5));return current<1?1:current<3?3:Math.round(current*2)}
function rateCard(rating){const card=data.flashcards.find(c=>c.id===currentCardId);if(!card)return;const days=nextInterval(card,rating);card.interval=days;card.reviews=(card.reviews||0)+1;const next=new Date();next.setDate(next.getDate()+days);card.due=next.toISOString().slice(0,10);answerVisible=false;currentCardId=null;save();renderAll();toast(days?'다음 복습: '+days+'일 후':'잠시 후 다시 보여드릴게요')}
function renderFocus(){const gaps=gapItems();document.querySelector('#focusGrid').innerHTML=gaps.map(o=>{const p=data.progress[o.id];return `<article class="focus-card"><div><code>${o.code} · ${SUBJECTS[o.subject].short}</code><h3>${o.title}</h3><p>${p.status==='progress'?'현재 학습 중':'학교 진도 완료 · Ivan 미완'} · 자신감 ${p.confidence||0}/5</p></div><button data-complete="${o.id}">완료로 표시</button></article>`}).join('')||'<div class="panel empty">멋집니다. 현재 학교 진도와 Ivan의 학습 사이에 Gap이 없습니다.</div>'}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function showUpdateBanner(version){const el=document.querySelector('#updateBanner');if(!el)return;el.querySelector('span').textContent=`새 버전 v${version}이 준비되었습니다.`;el.classList.add('show')}
async function applyAppUpdate(){try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.update()))}if(window.caches){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('ib-compass-')).map(k=>caches.delete(k)))}}catch(e){console.warn('Update refresh skipped cache cleanup',e)}location.replace(location.origin+location.pathname)}
async function checkForAppUpdate(){try{const res=await fetch(`version.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)return;const info=await res.json();if(info.version&&String(info.version)!==APP_VERSION)showUpdateBanner(info.version)}catch(e){}}
function openDialog(){const f=document.querySelector('#practiceForm');f.reset();f.elements.date.value=new Date().toISOString().slice(0,10);document.querySelector('#practiceDialog').showModal()}
function openCardDialog(){document.querySelector('#flashcardForm').reset();document.querySelector('#flashcardDialog').showModal()}
function findObjective(id){return Object.keys(SUBJECTS).flatMap(k=>allObjectives(k)).find(o=>o.id===id)}
function renderWorkspace(){const current=document.querySelector('#workspaceCurrent'),setup=document.querySelector('#workspaceSetup');if(!current||!setup)return;if(!activeWorkspace){current.innerHTML='';setup.classList.remove('hidden');return}setup.classList.add('hidden');const owner=activeWorkspace.member_role==='owner';current.innerHTML=`<div class="workspace-info"><span class="role-chip">${owner?'Owner · 부모':'Student · Ivan'}</span><h3>${escapeHtml(activeWorkspace.workspace_name)}</h3><p>${owner?'Syllabus를 관리하고 학생을 초대할 수 있습니다.':'진도, Practice와 Flashcard가 가족 계정과 공유됩니다.'}</p>${owner?`<div class="invite-box"><span><small>IVAN 초대 코드</small><br><code>${activeWorkspace.invite_code}</code></span><button type="button" data-copy-invite>코드 복사</button></div>`:`<p class="student-note">Syllabus 구조 변경은 Owner 계정에서 관리합니다.</p>`}</div>`}
function openObjectiveDialog(id){if(activeWorkspace&&activeWorkspace.member_role!=='owner'){toast('Syllabus 편집은 Owner만 가능합니다');return}const f=document.querySelector('#objectiveForm');f.reset();const o=id?findObjective(id):null;f.elements.originalId.value=o?o.id:'';f.elements.subject.value=o?o.subject:selectedSubject;f.elements.subject.disabled=!!o;f.elements.code.value=o?o.code:'';f.elements.group.value=o?o.group:'';f.elements.title.value=o?o.title:'';f.elements.category.value=o?o.category:'';f.elements.level.value=o&&o.level?o.level:'SL + HL';document.querySelector('#objectiveDialogTitle').textContent=o?'항목 수정':'항목 추가';document.querySelector('#archiveObjective').classList.toggle('hidden',!o);document.querySelector('#objectiveDialog').showModal()}
document.addEventListener('click',e=>{
  const closeButton=e.target.closest('.close, button[value="cancel"]');if(closeButton){e.preventDefault();const dialog=closeButton.closest('dialog');if(dialog)dialog.close();return}
  const loButton=e.target.closest('[data-open-lo]');if(loButton){openLearningObjectiveDrawer(loButton.dataset.openLo);return}
  const learningRow=e.target.closest('.has-learning-detail');if(learningRow&&!e.target.closest('select,button')){const codeEl=learningRow.querySelector('code'),code=codeEl?codeEl.textContent.trim():'',o=allObjectives('math').find(item=>item.code===code);if(o)openLearningObjectiveDrawer(o.id);return}
  const view=e.target.closest('[data-view]');if(view)switchView(view.dataset.view);
  const go=e.target.closest('[data-go]');if(go)switchView(go.dataset.go);
  const subject=e.target.closest('[data-subject]');if(subject){selectedSubject=subject.dataset.subject;renderSyllabus();renderLearningObjectives()}
  const open=e.target.closest('[data-subject-open]');if(open){selectedSubject=open.dataset.subjectOpen;renderSyllabus();renderLearningObjectives();switchView('syllabus')}
  const school=e.target.closest('[data-school]');if(school){data.progress[school.dataset.school].school=!data.progress[school.dataset.school].school;save();renderAll();toast('학교 진도를 업데이트했습니다')}
  const header=e.target.closest('.group-header');if(header)header.parentElement.classList.toggle('collapsed');
  const complete=e.target.closest('[data-complete]');if(complete){data.progress[complete.dataset.complete].status='done';data.progress[complete.dataset.complete].confidence=Math.max(3,data.progress[complete.dataset.complete].confidence||0);save();renderAll();toast('완료로 표시했습니다')}
  const edit=e.target.closest('[data-edit-objective]');if(edit)openObjectiveDialog(edit.dataset.editObjective);
  if(e.target.closest('[data-new-card]'))openCardDialog();
  if(e.target.closest('[data-flip-card]')){answerVisible=true;renderFlashcards()}
  const libraryCard=e.target.closest('[data-card-id]');if(libraryCard&&!e.target.closest('button')){currentCardId=libraryCard.dataset.cardId;answerVisible=false;renderFlashcards();return}
  const rate=e.target.closest('[data-rate]');if(rate)rateCard(rate.dataset.rate);
  const removeCard=e.target.closest('[data-delete-card]');if(removeCard&&confirm('이 Flashcard를 삭제할까요?')){data.flashcards=data.flashcards.filter(c=>c.id!==removeCard.dataset.deleteCard);save();renderAll();toast('카드를 삭제했습니다')}
  if(e.target.closest('[data-copy-invite]')&&activeWorkspace){navigator.clipboard.writeText(activeWorkspace.invite_code);toast('초대 코드를 복사했습니다')}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-status]')){const id=e.target.dataset.status;data.progress[id].status=e.target.value;if(e.target.value==='done'&&!data.progress[id].confidence)data.progress[id].confidence=3;save();renderAll();toast('학습 상태를 저장했습니다')}if(e.target.matches('[data-confidence]')){data.progress[e.target.dataset.confidence].confidence=+e.target.value;save();renderAll();toast('자신감을 저장했습니다')}});
document.querySelector('#searchInput').addEventListener('input',renderSyllabus);document.querySelector('#statusFilter').addEventListener('change',renderSyllabus);
document.querySelector('#quickAdd').addEventListener('click',openDialog);document.querySelector('#addPractice').addEventListener('click',openDialog);
document.querySelector('#addFlashcard').addEventListener('click',openCardDialog);document.querySelector('#addObjective').addEventListener('click',()=>openObjectiveDialog());
const updateNowButton=document.querySelector('#updateNow'),dismissUpdateButton=document.querySelector('#dismissUpdate');if(updateNowButton)updateNowButton.addEventListener('click',applyAppUpdate);if(dismissUpdateButton)dismissUpdateButton.addEventListener('click',()=>{const el=document.querySelector('#updateBanner');if(el)el.classList.remove('show')});
document.querySelector('#resetButton').addEventListener('click',()=>{if(confirm('저장된 변경사항을 지우고 샘플 상태로 되돌릴까요?')){localStorage.removeItem(KEY);data=loadData();save();renderAll();toast('샘플 데이터로 초기화했습니다')}});
const subjectSelect=document.querySelector('#practiceForm [name=subject]');subjectSelect.innerHTML=Object.entries(SUBJECTS).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('');
const subjectOptions=Object.entries(SUBJECTS).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('');document.querySelector('#flashcardForm [name=subject]').innerHTML=subjectOptions;document.querySelector('#objectiveForm [name=subject]').innerHTML=subjectOptions;document.querySelector('#cardSubjectFilter').innerHTML='<option value="all">모든 과목</option>'+subjectOptions;document.querySelector('#cardSubjectFilter').addEventListener('change',renderFlashcards);
document.querySelector('#savePractice').addEventListener('click',e=>{const f=document.querySelector('#practiceForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f);data.practice.push({date:fd.get('date'),subject:fd.get('subject'),name:fd.get('name'),topic:fd.get('topic'),score:+fd.get('score'),notes:fd.get('notes')});save();renderAll();toast('연습 기록을 저장했습니다')});
document.querySelector('#saveFlashcard').addEventListener('click',e=>{const f=document.querySelector('#flashcardForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f);data.flashcards.push({id:'card-'+Date.now(),subject:fd.get('subject'),code:fd.get('code'),type:fd.get('type'),tag:fd.get('tag'),front:fd.get('front'),back:fd.get('back'),due:today(),interval:0,reviews:0});currentCardId=null;save();renderAll();toast('Flashcard를 만들었습니다')});
document.querySelector('#saveObjective').addEventListener('click',e=>{const f=document.querySelector('#objectiveForm');if(!f.reportValidity()){e.preventDefault();return}const fd=new FormData(f),originalId=fd.get('originalId'),subject=f.elements.subject.value,values={subject,code:fd.get('code'),group:fd.get('group'),title:fd.get('title'),category:fd.get('category'),level:fd.get('level')};if(originalId){const custom=data.customObjectives.find(o=>o.id===originalId);if(custom)Object.assign(custom,values);else data.objectiveOverrides[originalId]=values}else{values.id=subject+'-custom-'+Date.now();values.custom=true;data.customObjectives.push(values);data.progress[values.id]={school:false,status:'todo',confidence:0}}save();renderAll();toast(originalId?'Syllabus 항목을 수정했습니다':'Syllabus 항목을 추가했습니다')});
document.querySelector('#archiveObjective').addEventListener('click',()=>{const id=document.querySelector('#objectiveForm').elements.originalId.value;if(id&&confirm('이 항목을 보관할까요? 기존 진도 기록은 유지됩니다.')){data.archivedObjectives.push(id);save();document.querySelector('#objectiveDialog').close();renderAll();toast('항목을 보관했습니다')}});
document.querySelector('#accountButton').addEventListener('click',()=>{if(cloudUser){renderWorkspace();document.querySelector('#workspaceError').textContent='';document.querySelector('#workspaceDialog').showModal()}else{document.querySelector('#authForm').reset();document.querySelector('#authError').textContent='';document.querySelector('#authDialog').showModal()}});
async function authenticate(mode){const form=document.querySelector('#authForm');if(!form.reportValidity())return;const email=form.elements.email.value.trim(),password=form.elements.password.value,errorEl=document.querySelector('#authError');errorEl.textContent='';if(!cloudClient){errorEl.textContent='Supabase에 연결할 수 없습니다.';return}const cfg=window.IB_SUPABASE_CONFIG||{};const result=mode==='signup'?await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:cfg.redirectUrl}}):await cloudClient.auth.signInWithPassword({email,password});if(result.error){errorEl.textContent=result.error.message;return}document.querySelector('#authDialog').close();if(mode==='signup'&&!result.data.session)toast('확인 이메일을 보냈습니다. 이메일 인증 후 로그인하세요.');else toast(mode==='signup'?'계정을 만들었습니다':'로그인했습니다')}
document.querySelector('#signUpButton').addEventListener('click',()=>authenticate('signup'));document.querySelector('#signInButton').addEventListener('click',()=>authenticate('signin'));
document.querySelector('#workspaceSignOut').addEventListener('click',async()=>{if(confirm('모든 기기에서 로그아웃할까요?')){document.querySelector('#workspaceDialog').close();await cloudClient.auth.signOut()}});
document.querySelector('#createWorkspace').addEventListener('click',async()=>{const form=document.querySelector('#workspaceForm'),name=form.elements.workspaceName.value.trim(),errorEl=document.querySelector('#workspaceError');errorEl.textContent='';if(!name){errorEl.textContent='Workspace 이름을 입력하세요.';return}const result=await cloudClient.rpc('create_family_workspace',{workspace_name:name});if(result.error){errorEl.textContent=result.error.message;return}await refreshWorkspace();await loadCloudData();renderWorkspace();toast('가족 Workspace를 만들었습니다')});
document.querySelector('#joinWorkspace').addEventListener('click',async()=>{const form=document.querySelector('#workspaceForm'),code=form.elements.inviteCode.value.trim().toUpperCase(),errorEl=document.querySelector('#workspaceError');errorEl.textContent='';if(code.length!==8){errorEl.textContent='8자리 초대 코드를 입력하세요.';return}const result=await cloudClient.rpc('join_family_workspace',{code});if(result.error){errorEl.textContent=result.error.message;return}await refreshWorkspace();await loadCloudData();renderWorkspace();toast('가족 Workspace에 참여했습니다')});
document.querySelector('#todayLabel').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js');
renderAll();
initCloud();
checkForAppUpdate();
